import { PassageType } from '../entities/passage.entity';

const P = (n: number) => `00000000-0000-0000-0000-${n.toString().padStart(12, '0')}`;
const Q = (n: number) => `10000000-0000-0000-0000-${n.toString().padStart(12, '0')}`;

export const socialSciencePassages = [
  {
    id: P(32),
    title: 'The Psychology of Habit Formation',
    type: PassageType.SOCIAL_SCIENCE,
    difficulty: 2,
    source: 'Adapted from research on behavioral psychology',
    text: `Psychologists have long studied how habits form and persist in human behavior. According to current research, habits develop through a three-stage process: cue, routine, and reward. The cue triggers the behavior, the routine is the behavior itself, and the reward reinforces the pattern. Over time, this loop becomes automatic, requiring minimal conscious thought.

What makes habits particularly powerful is their efficiency. The brain essentially "outsources" repeated behaviors to the basal ganglia, freeing up mental resources for other tasks. This neurological efficiency explains why breaking bad habits is so difficult—the neural pathways have been strengthened through repetition.

Recent studies suggest that the key to changing habits isn\'t willpower alone, but rather understanding and manipulating the cue-routine-reward cycle. By identifying triggers and substituting new routines while maintaining the same reward, individuals can successfully rewire their behavioral patterns. This approach, known as "habit substitution," has shown remarkable success in clinical settings.`,
    wordCount: 200,
    reviewStatus: 'approved',
  },
  {
    id: P(33),
    title: 'Urbanization and Mental Health',
    type: PassageType.SOCIAL_SCIENCE,
    difficulty: 3,
    source: 'Adapted from urban sociology research',
    text: `The rapid urbanization of the past century has fundamentally altered human living conditions, and researchers are increasingly concerned about its psychological effects. Studies consistently show that urban residents experience higher rates of anxiety disorders and depression compared to their rural counterparts. However, the relationship between city living and mental health is more nuanced than simple correlation suggests.

Urban environments present unique stressors: noise pollution, crowding, reduced access to nature, and what sociologists call "social fragmentation"—the weakening of community bonds in densely populated areas. Yet cities also offer advantages: better healthcare access, cultural opportunities, and economic mobility. The mental health impact appears to depend significantly on neighborhood characteristics and individual circumstances.

Researchers have identified several protective factors that buffer urban residents from psychological distress. Access to green spaces, even small parks, correlates with improved mental well-being. Strong social networks and community involvement also mitigate negative effects. These findings suggest that urban planning decisions—not urbanization itself—may be the crucial variable determining mental health outcomes in cities.`,
    wordCount: 210,
    reviewStatus: 'approved',
  },
  {
    id: P(34),
    title: 'Human Capital Theory and Education Economics',
    type: PassageType.SOCIAL_SCIENCE,
    difficulty: 4,
    source: 'Adapted from economic theory literature',
    text: `Human capital theory, developed by economists in the 1960s, treats education as an investment that enhances individual productivity and earning potential. The theory posits that rational actors will invest in education up to the point where marginal costs equal marginal benefits. This framework has profoundly influenced education policy, justifying public spending as an investment in economic growth rather than mere consumption.

Critics argue, however, that human capital theory oversimplifies the relationship between education and earnings. The "signaling model" offers an alternative explanation: educational credentials may primarily serve to signal pre-existing ability to employers rather than creating new productive capacity. If true, education functions more as a sorting mechanism than a true productivity enhancer, raising questions about the social value of educational expansion.

Empirical evidence presents a complex picture. While education clearly correlates with higher earnings, isolating education\'s causal effect proves difficult. Natural experiments—comparing individuals whose educational opportunities differed due to policy changes—suggest genuine returns to education, but these returns vary considerably across contexts and may be declining as credential inflation intensifies. The debate has significant implications for how societies should invest in and structure educational systems.`,
    wordCount: 220,
    reviewStatus: 'approved',
  },
  {
    id: P(35),
    title: 'Rawlsian Justice and Distributive Fairness',
    type: PassageType.SOCIAL_SCIENCE,
    difficulty: 5,
    source: 'Adapted from political philosophy',
    text: `John Rawls\'s theory of justice, articulated in his seminal 1971 work, fundamentally reoriented political philosophy by grounding principles of justice in a hypothetical "original position." In this thought experiment, rational individuals choose principles to govern their society from behind a "veil of ignorance," unaware of their eventual social position, talents, or preferences. Rawls argued that such individuals would rationally select two principles: equal basic liberties for all, and social and economic inequalities arranged to benefit the least advantaged (the "difference principle").

The difference principle represents a sophisticated middle ground between strict egalitarianism and libertarian theories that permit any inequality arising from voluntary exchange. Rawls contended that inequalities could be just if they incentivize productive behavior that ultimately improves the position of society\'s worst-off members. This challenges both purely meritocratic conceptions—which ignore how natural talents are arbitrary from a moral standpoint—and purely egalitarian ones—which might reduce overall welfare.

Critics have challenged Rawls on multiple fronts. Libertarians reject the premise that natural talents constitute a collective resource. Communitarians argue that justice principles cannot be derived independently of particular cultural contexts. Yet Rawls\'s framework continues to dominate contemporary discourse, its influence evident in debates over healthcare, education, and tax policy across democratic societies.`,
    wordCount: 230,
    reviewStatus: 'approved',
  },
  {
    id: P(36),
    title: 'Understanding the Bystander Effect',
    type: PassageType.SOCIAL_SCIENCE,
    difficulty: 1,
    source: 'Adapted from social psychology research',
    text: `In 1964, a woman named Kitty Genovese was attacked in New York City while dozens of neighbors witnessed the crime but failed to intervene or call for help. This tragedy prompted psychologists to investigate why people often don\'t help in emergencies when others are present—a phenomenon now known as the bystander effect.

Researchers have discovered two main psychological processes that explain this effect. First, there\'s "diffusion of responsibility": when multiple people witness an emergency, each individual feels less personal responsibility to act, assuming someone else will help. Second, "pluralistic ignorance" occurs when people look to others for cues about how to respond. If everyone appears calm, individuals may interpret the situation as less serious than it actually is.

Understanding the bystander effect has practical applications. Studies show that simply being aware of this tendency can help people overcome it. Training programs now teach individuals to take direct action in emergencies rather than waiting for others to respond. This research demonstrates how social psychology can identify problematic patterns in human behavior and help us develop strategies to counteract them.`,
    wordCount: 190,
    reviewStatus: 'approved',
  },
];

export const socialScienceQuestions = [
  // P32: The Psychology of Habit Formation (Q173-Q178)
  {
    id: Q(173),
    passageId: P(32),
    stem: 'Which of the following best describes the main idea of the passage?',
    choices: [
      { label: 'A', text: 'Habits are impossible to change once they are formed.' },
      { label: 'B', text: 'Understanding the structure of habits can help people modify their behaviors.' },
      { label: 'C', text: 'The basal ganglia is the most important part of the brain.' },
      { label: 'D', text: 'Willpower is the only factor needed to break bad habits.' },
    ],
    correctAnswer: 1,
    explanation: 'The passage emphasizes that understanding the cue-routine-reward cycle enables successful habit modification through substitution rather than willpower alone. This is the central theme developed throughout all three paragraphs.',
    hint: 'Look for the main point that connects all three paragraphs. What does the passage emphasize about changing habits?',
    difficulty: 2,
    skillIds: ['information_ideas.central_ideas'],
  },
  {
    id: Q(174),
    passageId: P(32),
    stem: 'As used in the passage, "outsources" most nearly means',
    choices: [
      { label: 'A', text: 'eliminates' },
      { label: 'B', text: 'delegates' },
      { label: 'C', text: 'publishes' },
      { label: 'D', text: 'discovers' },
    ],
    correctAnswer: 1,
    explanation: 'In this context, "outsources" means the brain delegates repeated behaviors to the basal ganglia, transferring the work to a different part of the brain. "Delegates" captures this meaning of assigning tasks to another entity.',
    hint: 'Consider what the brain is doing when it transfers repeated behaviors to a specific brain region. What word means transferring responsibility to someone or something else?',
    difficulty: 2,
    skillIds: ['rhetoric.words_in_context'],
  },
  {
    id: Q(175),
    passageId: P(32),
    stem: 'According to the passage, what makes breaking bad habits difficult?',
    choices: [
      { label: 'A', text: 'The basal ganglia stops functioning properly.' },
      { label: 'B', text: 'People lack awareness of their bad habits.' },
      { label: 'C', text: 'Neural pathways have been strengthened through repetition.' },
      { label: 'D', text: 'The three-stage process cannot be interrupted.' },
    ],
    correctAnswer: 2,
    explanation: 'The passage explicitly states that breaking bad habits is difficult because "the neural pathways have been strengthened through repetition." This directly answers the question.',
    hint: 'The passage provides a specific neurological explanation in the second paragraph. Look for direct information about why habits are hard to break.',
    difficulty: 1,
    skillIds: ['information_ideas.command_of_evidence'],
  },
  {
    id: Q(176),
    passageId: P(32),
    stem: 'The passage suggests that "habit substitution" works by',
    choices: [
      { label: 'A', text: 'completely eliminating the reward component' },
      { label: 'B', text: 'removing all environmental cues that trigger habits' },
      { label: 'C', text: 'replacing the routine while keeping the same reward' },
      { label: 'D', text: 'strengthening willpower through mental exercises' },
    ],
    correctAnswer: 2,
    explanation: 'The passage states that habit substitution involves "substituting new routines while maintaining the same reward." This directly describes the mechanism by which it works.',
    hint: 'The final paragraph describes how habit substitution works. Which component of the habit loop gets changed, and which stays the same?',
    difficulty: 2,
    skillIds: ['information_ideas.inferences'],
  },
  {
    id: Q(177),
    passageId: P(32),
    stem: 'The primary purpose of the second paragraph is to',
    choices: [
      { label: 'A', text: 'contradict the theory presented in the first paragraph' },
      { label: 'B', text: 'explain the neurological basis for habit efficiency' },
      { label: 'C', text: 'argue that habits are always beneficial' },
      { label: 'D', text: 'introduce a new method for changing habits' },
    ],
    correctAnswer: 1,
    explanation: 'The second paragraph explains why habits are powerful by describing how the brain makes them efficient through the basal ganglia, providing the neurological explanation for the phenomenon introduced in the first paragraph.',
    hint: 'Consider what new information the second paragraph adds to the discussion. What aspect of habits does it focus on?',
    difficulty: 3,
    skillIds: ['rhetoric.text_structure', 'rhetoric.purpose'],
  },
  {
    id: Q(178),
    passageId: P(32),
    stem: 'Which statement best describes the relationship between willpower and habit change as presented in the passage?',
    choices: [
      { label: 'A', text: 'Willpower is completely unnecessary for changing habits.' },
      { label: 'B', text: 'Willpower alone is insufficient; understanding habit structure is also important.' },
      { label: 'C', text: 'Willpower is the most reliable method for changing any behavior.' },
      { label: 'D', text: 'Willpower and habit substitution cannot be used together.' },
    ],
    correctAnswer: 1,
    explanation: 'The passage states that "the key to changing habits isn\'t willpower alone" but rather understanding the habit cycle, indicating that willpower by itself is insufficient and must be combined with structural understanding.',
    hint: 'Look at what the passage says about willpower in the third paragraph. Does it say willpower is useless, or does it qualify its role?',
    difficulty: 3,
    skillIds: ['information_ideas.inferences', 'rhetoric.arguments'],
  },

  // P33: Urbanization and Mental Health (Q179-Q184)
  {
    id: Q(179),
    passageId: P(33),
    stem: 'The main purpose of the passage is to',
    choices: [
      { label: 'A', text: 'argue that cities should be abandoned for rural living' },
      { label: 'B', text: 'present a nuanced view of how urbanization affects mental health' },
      { label: 'C', text: 'prove that urban living always causes depression' },
      { label: 'D', text: 'describe the history of urbanization' },
    ],
    correctAnswer: 1,
    explanation: 'The passage explicitly states that "the relationship between city living and mental health is more nuanced than simple correlation suggests" and proceeds to examine both negative and positive aspects, along with protective factors.',
    hint: 'The second sentence of the first paragraph signals the passage\'s approach. How does the author characterize the relationship being examined?',
    difficulty: 2,
    skillIds: ['rhetoric.purpose'],
  },
  {
    id: Q(180),
    passageId: P(33),
    stem: 'According to the passage, "social fragmentation" refers to',
    choices: [
      { label: 'A', text: 'the physical breaking apart of neighborhoods' },
      { label: 'B', text: 'the weakening of community bonds in populated areas' },
      { label: 'C', text: 'the separation of different social classes' },
      { label: 'D', text: 'the reduction in family size over time' },
    ],
    correctAnswer: 1,
    explanation: 'The passage explicitly defines "social fragmentation" as "the weakening of community bonds in densely populated areas." This is a direct definition provided in the text.',
    hint: 'The passage provides a specific definition right after introducing the term. Look for the dash that signals the explanation.',
    difficulty: 1,
    skillIds: ['rhetoric.words_in_context', 'information_ideas.command_of_evidence'],
  },
  {
    id: Q(181),
    passageId: P(33),
    stem: 'Which of the following is NOT mentioned as a stressor unique to urban environments?',
    choices: [
      { label: 'A', text: 'Noise pollution' },
      { label: 'B', text: 'Overcrowding' },
      { label: 'C', text: 'Increased crime rates' },
      { label: 'D', text: 'Reduced access to nature' },
    ],
    correctAnswer: 2,
    explanation: 'The passage lists noise pollution, crowding, reduced access to nature, and social fragmentation as urban stressors. Crime rates are not mentioned anywhere in the passage.',
    hint: 'Carefully review the list of stressors in the second paragraph. Which option doesn\'t appear in that list?',
    difficulty: 2,
    skillIds: ['information_ideas.command_of_evidence'],
  },
  {
    id: Q(182),
    passageId: P(33),
    stem: 'The passage suggests that the mental health impact of urban living primarily depends on',
    choices: [
      { label: 'A', text: 'the size of the city' },
      { label: 'B', text: 'neighborhood characteristics and individual circumstances' },
      { label: 'C', text: 'the climate of the region' },
      { label: 'D', text: 'the city\'s economic development level' },
    ],
    correctAnswer: 1,
    explanation: 'The passage states that "the mental health impact appears to depend significantly on neighborhood characteristics and individual circumstances," directly identifying these as the primary determining factors.',
    hint: 'Look at the end of the second paragraph for what the passage identifies as important determining factors.',
    difficulty: 2,
    skillIds: ['information_ideas.inferences'],
  },
  {
    id: Q(183),
    passageId: P(33),
    stem: 'The final paragraph primarily serves to',
    choices: [
      { label: 'A', text: 'contradict the negative effects described earlier' },
      { label: 'B', text: 'identify factors that can reduce negative mental health impacts' },
      { label: 'C', text: 'call for the elimination of cities' },
      { label: 'D', text: 'criticize current urban planning practices' },
    ],
    correctAnswer: 1,
    explanation: 'The third paragraph focuses on "protective factors that buffer urban residents from psychological distress," identifying specific elements that can mitigate negative effects.',
    hint: 'What is the main focus of the examples given in the third paragraph—green spaces and social networks?',
    difficulty: 3,
    skillIds: ['rhetoric.text_structure'],
  },
  {
    id: Q(184),
    passageId: P(33),
    stem: 'The passage\'s conclusion that "urban planning decisions—not urbanization itself—may be the crucial variable" suggests that',
    choices: [
      { label: 'A', text: 'cities are inherently harmful to mental health' },
      { label: 'B', text: 'rural areas always provide better mental health outcomes' },
      { label: 'C', text: 'how cities are designed matters more than whether people live in cities' },
      { label: 'D', text: 'mental health problems cannot be addressed in urban settings' },
    ],
    correctAnswer: 2,
    explanation: 'By distinguishing between urbanization itself and urban planning decisions, the passage suggests that the design and organization of cities (planning) is more important than the mere fact of living in cities (urbanization).',
    hint: 'The passage makes a distinction between two things: living in cities versus how cities are designed. Which does it identify as more important?',
    difficulty: 4,
    skillIds: ['information_ideas.inferences', 'rhetoric.arguments'],
  },

  // P34: Human Capital Theory and Education Economics (Q185-Q190)
  {
    id: Q(185),
    passageId: P(34),
    stem: 'The primary purpose of the passage is to',
    choices: [
      { label: 'A', text: 'advocate for increased public spending on education' },
      { label: 'B', text: 'present human capital theory and discuss challenges to it' },
      { label: 'C', text: 'prove that education has no real economic value' },
      { label: 'D', text: 'explain why education costs have increased' },
    ],
    correctAnswer: 1,
    explanation: 'The passage introduces human capital theory in the first paragraph, presents the signaling model critique in the second, and discusses empirical evidence in the third, providing a balanced examination of the theory and its challenges.',
    hint: 'Consider the overall structure: the passage introduces a theory, then presents criticisms, then discusses evidence. What is the author trying to do?',
    difficulty: 3,
    skillIds: ['rhetoric.purpose'],
  },
  {
    id: Q(186),
    passageId: P(34),
    stem: 'According to human capital theory, rational individuals will invest in education until',
    choices: [
      { label: 'A', text: 'they run out of money' },
      { label: 'B', text: 'they achieve the highest degree possible' },
      { label: 'C', text: 'marginal costs equal marginal benefits' },
      { label: 'D', text: 'employers require more credentials' },
    ],
    correctAnswer: 2,
    explanation: 'The passage explicitly states that "rational actors will invest in education up to the point where marginal costs equal marginal benefits." This is a direct statement from the first paragraph.',
    hint: 'Look at the first paragraph for the specific economic principle that determines how much education rational actors pursue.',
    difficulty: 2,
    skillIds: ['information_ideas.command_of_evidence'],
  },
  {
    id: Q(187),
    passageId: P(34),
    stem: 'The "signaling model" differs from human capital theory in that it views education primarily as',
    choices: [
      { label: 'A', text: 'a way to create productive capacity' },
      { label: 'B', text: 'an indicator of pre-existing ability rather than a creator of new skills' },
      { label: 'C', text: 'a waste of economic resources' },
      { label: 'D', text: 'a method to reduce social inequality' },
    ],
    correctAnswer: 1,
    explanation: 'The passage states that in the signaling model, "educational credentials may primarily serve to signal pre-existing ability to employers rather than creating new productive capacity," contrasting it with human capital theory\'s view.',
    hint: 'The second paragraph contrasts the two theories. What does the signaling model say education does instead of creating productivity?',
    difficulty: 3,
    skillIds: ['information_ideas.inferences', 'rhetoric.arguments'],
  },
  {
    id: Q(188),
    passageId: P(34),
    stem: 'As used in the passage, "isolating" most nearly means',
    choices: [
      { label: 'A', text: 'separating' },
      { label: 'B', text: 'determining' },
      { label: 'C', text: 'quarantining' },
      { label: 'D', text: 'excluding' },
    ],
    correctAnswer: 1,
    explanation: 'In this context, "isolating education\'s causal effect" means determining or identifying the specific effect that education has separate from other factors. "Determining" best captures this meaning of identifying a specific causal relationship.',
    hint: 'Consider what researchers are trying to do when they study education\'s effect. What word means figuring out or identifying something specific?',
    difficulty: 4,
    skillIds: ['rhetoric.words_in_context'],
  },
  {
    id: Q(189),
    passageId: P(34),
    stem: 'The passage mentions "natural experiments" as a way to',
    choices: [
      { label: 'A', text: 'prove that education has no value' },
      { label: 'B', text: 'test educational theories in laboratory settings' },
      { label: 'C', text: 'better identify the causal effect of education by comparing similar individuals' },
      { label: 'D', text: 'reduce the cost of educational research' },
    ],
    correctAnswer: 2,
    explanation: 'The passage describes natural experiments as "comparing individuals whose educational opportunities differed due to policy changes" and notes these "suggest genuine returns to education," indicating they help establish causal effects.',
    hint: 'Why would comparing people whose educational opportunities differed due to policy changes be useful for researchers studying causation?',
    difficulty: 3,
    skillIds: ['information_ideas.inferences'],
  },
  {
    id: Q(190),
    passageId: P(34),
    stem: 'The passage suggests that "credential inflation" refers to',
    choices: [
      { label: 'A', text: 'the increasing cost of obtaining degrees' },
      { label: 'B', text: 'the declining value of educational credentials as they become more common' },
      { label: 'C', text: 'the falsification of educational records' },
      { label: 'D', text: 'the expansion of online degree programs' },
    ],
    correctAnswer: 1,
    explanation: 'The passage mentions that returns to education "may be declining as credential inflation intensifies," suggesting that as more people obtain credentials, their value decreases—similar to how monetary inflation reduces purchasing power.',
    hint: 'Think about what "inflation" means in economics. How might that concept apply to educational credentials?',
    difficulty: 4,
    skillIds: ['rhetoric.words_in_context', 'information_ideas.inferences'],
  },

  // P35: Rawlsian Justice and Distributive Fairness (Q191-Q196)
  {
    id: Q(191),
    passageId: P(35),
    stem: 'The main purpose of the passage is to',
    choices: [
      { label: 'A', text: 'explain Rawls\'s theory of justice and present criticisms of it' },
      { label: 'B', text: 'prove that libertarian theories are superior to Rawls\'s approach' },
      { label: 'C', text: 'describe the history of political philosophy' },
      { label: 'D', text: 'argue for strict economic equality in all societies' },
    ],
    correctAnswer: 0,
    explanation: 'The passage systematically presents Rawls\'s theory in the first two paragraphs and then discusses various criticisms in the third, making explanation and critical examination its primary purpose.',
    hint: 'Consider the structure: the passage explains a theory and then discusses challenges to it. What is the author\'s overall goal?',
    difficulty: 3,
    skillIds: ['rhetoric.purpose'],
  },
  {
    id: Q(192),
    passageId: P(35),
    stem: 'According to the passage, the "veil of ignorance" ensures that principles of justice are chosen',
    choices: [
      { label: 'A', text: 'by the wealthiest members of society' },
      { label: 'B', text: 'without knowledge of one\'s eventual position in society' },
      { label: 'C', text: 'based on historical precedent' },
      { label: 'D', text: 'through democratic voting' },
    ],
    correctAnswer: 1,
    explanation: 'The passage states that in the original position, individuals choose principles "from behind a \'veil of ignorance,\' unaware of their eventual social position, talents, or preferences."',
    hint: 'Look at the first paragraph\'s description of the veil of ignorance. What specific information are people denied?',
    difficulty: 2,
    skillIds: ['information_ideas.command_of_evidence'],
  },
  {
    id: Q(193),
    passageId: P(35),
    stem: 'The "difference principle" permits economic inequalities only when they',
    choices: [
      { label: 'A', text: 'result from voluntary exchanges' },
      { label: 'B', text: 'reflect differences in natural talent' },
      { label: 'C', text: 'benefit the least advantaged members of society' },
      { label: 'D', text: 'increase overall economic efficiency' },
    ],
    correctAnswer: 2,
    explanation: 'The passage explicitly states that the difference principle involves "social and economic inequalities arranged to benefit the least advantaged." This is the core requirement of the principle.',
    hint: 'The first paragraph directly states when inequalities are acceptable under the difference principle. Look for the specific condition mentioned.',
    difficulty: 2,
    skillIds: ['information_ideas.command_of_evidence'],
  },
  {
    id: Q(194),
    passageId: P(35),
    stem: 'As used in the passage, "arbitrary" most nearly means',
    choices: [
      { label: 'A', text: 'random or undeserved' },
      { label: 'B', text: 'carefully chosen' },
      { label: 'C', text: 'tyrannical' },
      { label: 'D', text: 'beneficial' },
    ],
    correctAnswer: 0,
    explanation: 'The passage states that natural talents are "arbitrary from a moral standpoint," meaning they are morally random or undeserved—people don\'t morally earn their natural abilities. "Random or undeserved" captures this moral arbitrariness.',
    hint: 'Consider what Rawls means when he says natural talents are arbitrary from a moral standpoint. Did people earn or deserve their natural abilities?',
    difficulty: 4,
    skillIds: ['rhetoric.words_in_context'],
  },
  {
    id: Q(195),
    passageId: P(35),
    stem: 'The passage suggests that libertarian critics of Rawls would most likely argue that',
    choices: [
      { label: 'A', text: 'natural talents should be considered collective resources' },
      { label: 'B', text: 'individuals have full moral claim to their natural abilities and what they produce' },
      { label: 'C', text: 'justice cannot exist in any society' },
      { label: 'D', text: 'strict equality should be enforced by the government' },
    ],
    correctAnswer: 1,
    explanation: 'The passage states that "Libertarians reject the premise that natural talents constitute a collective resource," implying they believe individuals have sole moral claim to their talents and their products.',
    hint: 'If libertarians reject the idea that natural talents are collective resources, what must they believe about who has claim to those talents?',
    difficulty: 4,
    skillIds: ['information_ideas.inferences', 'rhetoric.arguments'],
  },
  {
    id: Q(196),
    passageId: P(35),
    stem: 'According to the passage, communitarian critics of Rawls argue that',
    choices: [
      { label: 'A', text: 'inequalities should always benefit the wealthy' },
      { label: 'B', text: 'justice principles must be derived from specific cultural contexts' },
      { label: 'C', text: 'the veil of ignorance is the best method for determining justice' },
      { label: 'D', text: 'natural talents are morally arbitrary' },
    ],
    correctAnswer: 1,
    explanation: 'The passage states that "Communitarians argue that justice principles cannot be derived independently of particular cultural contexts," directly expressing their criticism of Rawls\'s universal approach.',
    hint: 'Look at what the passage says about communitarian criticism. What do they say about how justice principles should be derived?',
    difficulty: 3,
    skillIds: ['information_ideas.command_of_evidence'],
  },

  // P36: Understanding the Bystander Effect (Q197-Q202)
  {
    id: Q(197),
    passageId: P(36),
    stem: 'The primary purpose of the passage is to',
    choices: [
      { label: 'A', text: 'criticize people who fail to help in emergencies' },
      { label: 'B', text: 'explain the bystander effect and its practical applications' },
      { label: 'C', text: 'recount the details of the Kitty Genovese case' },
      { label: 'D', text: 'prove that people are fundamentally selfish' },
    ],
    correctAnswer: 1,
    explanation: 'The passage introduces the bystander effect through an example, explains its psychological causes, and then discusses practical applications of understanding it, making explanation and application its primary purpose.',
    hint: 'Consider what the passage does overall: it introduces a concept, explains it, and then discusses how understanding it is useful. What is the author\'s main goal?',
    difficulty: 2,
    skillIds: ['rhetoric.purpose'],
  },
  {
    id: Q(198),
    passageId: P(36),
    stem: 'According to the passage, "diffusion of responsibility" occurs when',
    choices: [
      { label: 'A', text: 'people are alone during an emergency' },
      { label: 'B', text: 'individuals feel less personal obligation because others are present' },
      { label: 'C', text: 'emergencies happen in rural areas' },
      { label: 'D', text: 'people misinterpret the seriousness of a situation' },
    ],
    correctAnswer: 1,
    explanation: 'The passage defines diffusion of responsibility as occurring "when multiple people witness an emergency, each individual feels less personal responsibility to act, assuming someone else will help."',
    hint: 'The second paragraph provides a clear definition of diffusion of responsibility. What happens to individual feelings of responsibility when others are present?',
    difficulty: 1,
    skillIds: ['information_ideas.command_of_evidence'],
  },
  {
    id: Q(199),
    passageId: P(36),
    stem: 'As used in the passage, "cues" most nearly means',
    choices: [
      { label: 'A', text: 'signals' },
      { label: 'B', text: 'questions' },
      { label: 'C', text: 'commands' },
      { label: 'D', text: 'memories' },
    ],
    correctAnswer: 0,
    explanation: 'In the context of "people look to others for cues about how to respond," cues refers to signals or indicators that guide behavior. "Signals" best captures this meaning.',
    hint: 'When people look to others for cues about how to respond, what are they looking for? What word means hints or indicators?',
    difficulty: 1,
    skillIds: ['rhetoric.words_in_context'],
  },
  {
    id: Q(200),
    passageId: P(36),
    stem: 'The passage suggests that "pluralistic ignorance" can lead people to',
    choices: [
      { label: 'A', text: 'overreact to minor situations' },
      { label: 'B', text: 'misinterpret a serious situation as less urgent than it is' },
      { label: 'C', text: 'immediately call for help in any emergency' },
      { label: 'D', text: 'ignore their own observations completely' },
    ],
    correctAnswer: 1,
    explanation: 'The passage states that with pluralistic ignorance, "If everyone appears calm, individuals may interpret the situation as less serious than it actually is," indicating underestimation of urgency.',
    hint: 'According to the passage, what happens when people see others appearing calm during an emergency?',
    difficulty: 2,
    skillIds: ['information_ideas.inferences'],
  },
  {
    id: Q(201),
    passageId: P(36),
    stem: 'Which of the following does the passage suggest is an effective way to overcome the bystander effect?',
    choices: [
      { label: 'A', text: 'Avoiding crowded places' },
      { label: 'B', text: 'Being aware of the tendency and trained to take direct action' },
      { label: 'C', text: 'Waiting to see if the situation resolves itself' },
      { label: 'D', text: 'Assuming someone else will handle emergencies' },
    ],
    correctAnswer: 1,
    explanation: 'The passage states that "simply being aware of this tendency can help people overcome it" and that "training programs now teach individuals to take direct action," identifying awareness and training as effective approaches.',
    hint: 'The third paragraph discusses solutions. What does the passage say helps people overcome the bystander effect?',
    difficulty: 2,
    skillIds: ['information_ideas.command_of_evidence'],
  },
  {
    id: Q(202),
    passageId: P(36),
    stem: 'The passage\'s discussion of the Kitty Genovese case primarily serves to',
    choices: [
      { label: 'A', text: 'provide a real-world example that prompted research into the bystander effect' },
      { label: 'B', text: 'prove that New York City is a dangerous place' },
      { label: 'C', text: 'demonstrate that the bystander effect cannot be overcome' },
      { label: 'D', text: 'criticize the neighbors who witnessed the crime' },
    ],
    correctAnswer: 0,
    explanation: 'The passage introduces the Genovese case and states "This tragedy prompted psychologists to investigate" the bystander effect, clearly identifying it as the historical catalyst for research rather than as an end in itself.',
    hint: 'Consider why the author mentions this case at the beginning. What role does it play in the passage\'s overall structure?',
    difficulty: 2,
    skillIds: ['rhetoric.text_structure', 'rhetoric.purpose'],
  },
];
