import { PassageType } from '../entities/passage.entity';

const P = (n: number) => `00000000-0000-0000-0000-${n.toString().padStart(12, '0')}`;
const Q = (n: number) => `10000000-0000-0000-0000-${n.toString().padStart(12, '0')}`;

export const sciencePassages = [
  {
    id: P(27),
    title: 'How Vaccines Protect Us',
    type: PassageType.SCIENCE,
    difficulty: 2,
    source: 'Adapted from immunology educational materials',
    text: `Vaccines are one of the most effective tools in preventing infectious diseases. When a vaccine is administered, it introduces a weakened or inactive form of a pathogen—or sometimes just a piece of it—into the body. This exposure is not strong enough to cause illness, but it is sufficient to trigger the immune system\'s response.

The immune system recognizes the vaccine components as foreign invaders and begins producing antibodies, which are proteins designed to fight off the specific pathogen. More importantly, the immune system creates memory cells that "remember" the pathogen. If the vaccinated person later encounters the actual disease-causing organism, these memory cells enable the immune system to respond rapidly and effectively, often preventing the disease entirely or reducing its severity.

This process, known as immunization, has led to the near-elimination of diseases like polio and measles in many parts of the world. Widespread vaccination also creates herd immunity, where enough people in a community are immune that disease transmission becomes difficult, thereby protecting even those who cannot be vaccinated, such as infants or individuals with compromised immune systems.`,
    wordCount: 200,
    reviewStatus: 'approved',
  },
  {
    id: P(28),
    title: 'Life in the Deep: Hydrothermal Vent Ecosystems',
    type: PassageType.SCIENCE,
    difficulty: 3,
    source: 'Adapted from marine biology research',
    text: `Deep beneath the ocean\'s surface, where sunlight cannot penetrate, scientists have discovered thriving ecosystems around hydrothermal vents—fissures in the seafloor that release superheated, mineral-rich water. These environments, found at depths exceeding 2,000 meters, challenge our fundamental understanding of how life can exist.

Unlike most ecosystems on Earth, which ultimately depend on photosynthesis for energy, hydrothermal vent communities rely on chemosynthesis. Specialized bacteria use the chemical energy from compounds like hydrogen sulfide, released by the vents, to produce organic matter. These bacteria form the base of a unique food web, supporting organisms such as giant tube worms, blind shrimp, and unusual species of crabs and fish.

The discovery of these ecosystems in 1977 revolutionized biology, demonstrating that life could thrive in conditions previously thought uninhabitable. The extreme pressure, near-freezing temperatures just meters away from boiling vent fluids, and complete absence of light create a harsh environment. Yet organisms have evolved remarkable adaptations, including symbiotic relationships with chemosynthetic bacteria and specialized proteins that function under extreme conditions. These findings have profound implications for our understanding of life\'s resilience and have even informed the search for extraterrestrial life on planets and moons with similar extreme environments.`,
    wordCount: 210,
    reviewStatus: 'approved',
  },
  {
    id: P(29),
    title: 'Neuroplasticity: The Adaptive Brain',
    type: PassageType.SCIENCE,
    difficulty: 4,
    source: 'Adapted from neuroscience research',
    text: `For much of the twentieth century, neuroscientists believed that the adult brain was relatively fixed in structure, with limited capacity for change after a critical developmental period. This view has been fundamentally challenged by mounting evidence of neuroplasticity—the brain\'s remarkable ability to reorganize itself by forming new neural connections throughout life.

Neuroplasticity manifests at multiple levels, from molecular changes at individual synapses to large-scale cortical remapping. When learning occurs, synaptic strength can be modified through processes called long-term potentiation and long-term depression, which strengthen or weaken connections between neurons. More dramatically, studies of individuals who have lost sensory functions reveal that brain regions originally dedicated to the lost sense can be "recruited" for other purposes. For instance, in blind individuals, the visual cortex—normally processing visual information—can be co-opted for enhanced auditory or tactile processing.

This plasticity has therapeutic implications. Stroke patients can sometimes recover lost functions as undamaged brain regions assume responsibilities of damaged areas. However, neuroplasticity is constrained by factors including age, with younger brains generally showing greater malleability, and the nature of the injury or learning task. Understanding the mechanisms and limitations of neuroplasticity remains a central challenge in neuroscience, with potential applications ranging from rehabilitation strategies to educational methods optimized for how the brain actually learns.`,
    wordCount: 220,
    reviewStatus: 'approved',
  },
  {
    id: P(30),
    title: 'The Dark Universe: Matter and Energy Beyond Detection',
    type: PassageType.SCIENCE,
    difficulty: 5,
    source: 'Adapted from cosmology research',
    text: `Contemporary cosmology confronts a profound paradox: the visible matter comprising stars, planets, and interstellar gas constitutes merely 5% of the universe\'s total energy density. The remaining 95% consists of dark matter and dark energy—components that neither emit nor absorb electromagnetic radiation, rendering them invisible to telescopes yet whose existence is inferred from their gravitational effects.

Dark matter, comprising approximately 27% of the universe, reveals itself through its gravitational influence on visible matter and light. Galaxies rotate at speeds that would tear them apart if only visible matter were present; the additional gravity from dark matter provides the necessary cohesion. Gravitational lensing observations—where massive objects bend light from distant sources—further corroborate dark matter\'s existence, as the observed lensing exceeds what visible matter alone could produce. Despite extensive searches, dark matter particles have eluded direct detection, leading to competing hypotheses including weakly interacting massive particles (WIMPs) and modifications to gravitational theory itself.

Dark energy, constituting roughly 68% of the universe, is even more enigmatic. Its existence was inferred from observations showing that the universe\'s expansion is accelerating—a phenomenon requiring a repulsive force counteracting gravity. The cosmological constant, originally proposed by Einstein and later abandoned, has been resurrected as a leading explanation, though its theoretical value differs from observations by an astounding factor of 10^120. Alternative theories invoke dynamic fields or modifications to general relativity. Resolving these mysteries represents perhaps the most significant challenge in fundamental physics.`,
    wordCount: 230,
    reviewStatus: 'approved',
  },
  {
    id: P(31),
    title: 'The Water Cycle: Earth\'s Natural Recycling System',
    type: PassageType.SCIENCE,
    difficulty: 1,
    source: 'Adapted from earth science educational materials',
    text: `Water is constantly moving through Earth\'s systems in a process called the water cycle. This cycle has no beginning or end—water simply changes form and location as it circulates between the oceans, atmosphere, and land.

The cycle begins when the sun heats water in oceans, lakes, and rivers, causing it to evaporate and turn into water vapor. Plants also release water vapor through their leaves in a process called transpiration. This water vapor rises into the atmosphere, where cooler temperatures cause it to condense into tiny droplets that form clouds.

When these droplets combine and become heavy enough, they fall back to Earth as precipitation—rain, snow, sleet, or hail. Some of this water flows across the land surface as runoff, eventually returning to oceans and lakes. Some soaks into the ground, replenishing underground aquifers, while some is absorbed by plants. The water that reaches the oceans or stays on the surface then begins the cycle again through evaporation. This continuous process ensures that Earth\'s water is constantly being purified and redistributed, supporting all life on the planet.`,
    wordCount: 190,
    reviewStatus: 'approved',
  },
];

export const scienceQuestions = [
  // P27 Questions (Q143-Q148)
  {
    id: Q(143),
    passageId: P(27),
    stem: 'What is the primary purpose of this passage?',
    choices: [
      { label: 'A', text: 'To describe the history of vaccine development' },
      { label: 'B', text: 'To explain how vaccines train the immune system to fight diseases' },
      { label: 'C', text: 'To argue that all people should receive vaccinations' },
      { label: 'D', text: 'To compare different types of vaccines available today' },
    ],
    correctAnswer: 1,
    explanation: 'The passage primarily explains the mechanism of how vaccines work—introducing weakened pathogens to trigger immune response and create memory cells. While it mentions herd immunity, the main focus is on explaining the immunization process.',
    hint: 'Focus on what the passage spends most of its time explaining rather than arguments or comparisons it makes.',
    difficulty: 2,
    skillIds: ['information_ideas.central_ideas', 'passage_type_proficiency.science_passages'],
  },
  {
    id: Q(144),
    passageId: P(27),
    stem: 'According to the passage, what role do memory cells play in vaccination?',
    choices: [
      { label: 'A', text: 'They produce the weakened pathogens used in vaccines' },
      { label: 'B', text: 'They prevent any foreign substance from entering the body' },
      { label: 'C', text: 'They enable rapid immune response when encountering the actual pathogen' },
      { label: 'D', text: 'They eliminate the need for antibodies in fighting infection' },
    ],
    correctAnswer: 2,
    explanation: 'The passage states that memory cells "remember" the pathogen and enable the immune system to respond rapidly and effectively when the vaccinated person later encounters the actual disease-causing organism.',
    hint: 'Look for the specific description of what memory cells do after initial vaccination.',
    difficulty: 2,
    skillIds: ['information_ideas.command_of_evidence', 'passage_type_proficiency.science_passages'],
  },
  {
    id: Q(145),
    passageId: P(27),
    stem: 'As used in the passage, "trigger" most nearly means',
    choices: [
      { label: 'A', text: 'activate' },
      { label: 'B', text: 'delay' },
      { label: 'C', text: 'suppress' },
      { label: 'D', text: 'destroy' },
    ],
    correctAnswer: 0,
    explanation: 'In this context, "trigger" means to initiate or activate the immune system\'s response. The vaccine causes the immune system to begin its defensive process.',
    hint: 'Consider what the vaccine does to the immune system—does it start something or stop something?',
    difficulty: 1,
    skillIds: ['rhetoric.words_in_context', 'passage_type_proficiency.science_passages'],
  },
  {
    id: Q(146),
    passageId: P(27),
    stem: 'Based on the passage, which statement about herd immunity is most accurate?',
    choices: [
      { label: 'A', text: 'It requires every single person in a community to be vaccinated' },
      { label: 'B', text: 'It protects vulnerable individuals by making disease transmission difficult' },
      { label: 'C', text: 'It is more effective than individual vaccination' },
      { label: 'D', text: 'It only works for diseases like polio and measles' },
    ],
    correctAnswer: 1,
    explanation: 'The passage explains that herd immunity occurs when enough people are immune that disease transmission becomes difficult, thereby protecting those who cannot be vaccinated, such as infants or immunocompromised individuals.',
    hint: 'The passage mentions specific groups who benefit from herd immunity even though they aren\'t vaccinated themselves.',
    difficulty: 3,
    skillIds: ['information_ideas.inferences', 'passage_type_proficiency.science_passages'],
  },
  {
    id: Q(147),
    passageId: P(27),
    stem: 'The passage indicates that vaccines contain',
    choices: [
      { label: 'A', text: 'antibodies harvested from immune individuals' },
      { label: 'B', text: 'weakened or inactive forms of pathogens or their components' },
      { label: 'C', text: 'memory cells that directly fight disease' },
      { label: 'D', text: 'strong doses of disease-causing organisms' },
    ],
    correctAnswer: 1,
    explanation: 'The first paragraph explicitly states that vaccines introduce "a weakened or inactive form of a pathogen—or sometimes just a piece of it—into the body."',
    hint: 'Look at the first paragraph\'s description of what vaccines actually introduce into the body.',
    difficulty: 1,
    skillIds: ['information_ideas.command_of_evidence', 'passage_type_proficiency.science_passages'],
  },
  {
    id: Q(148),
    passageId: P(27),
    stem: 'Which statement best describes the relationship between antibodies and memory cells as presented in the passage?',
    choices: [
      { label: 'A', text: 'Antibodies create memory cells for long-term protection' },
      { label: 'B', text: 'Memory cells produce antibodies during the initial vaccine response' },
      { label: 'C', text: 'Both are produced during immune response, but memory cells provide lasting protection' },
      { label: 'D', text: 'They serve identical functions in the immune system' },
    ],
    correctAnswer: 2,
    explanation: 'The passage explains that the immune system produces antibodies to fight the pathogen and creates memory cells that remember it. The memory cells are emphasized as providing the lasting benefit—they enable rapid response upon future exposure.',
    hint: 'Consider what happens during vaccination versus what provides long-term protection.',
    difficulty: 3,
    skillIds: ['information_ideas.inferences', 'rhetoric.text_structure', 'passage_type_proficiency.science_passages'],
  },

  // P28 Questions (Q149-Q154)
  {
    id: Q(149),
    passageId: P(28),
    stem: 'The primary purpose of the passage is to',
    choices: [
      { label: 'A', text: 'argue that hydrothermal vents are the origin of all life on Earth' },
      { label: 'B', text: 'describe unique deep-sea ecosystems and their significance to biology' },
      { label: 'C', text: 'compare photosynthesis and chemosynthesis in detail' },
      { label: 'D', text: 'explain how to search for extraterrestrial life' },
    ],
    correctAnswer: 1,
    explanation: 'The passage introduces hydrothermal vent ecosystems, explains how they function differently from other ecosystems, and discusses their significance to our understanding of life\'s resilience and adaptability.',
    hint: 'What is the main topic the passage explores, and why does the author find it important?',
    difficulty: 2,
    skillIds: ['information_ideas.central_ideas', 'rhetoric.purpose', 'passage_type_proficiency.science_passages'],
  },
  {
    id: Q(150),
    passageId: P(28),
    stem: 'According to the passage, how do hydrothermal vent ecosystems differ fundamentally from most other ecosystems on Earth?',
    choices: [
      { label: 'A', text: 'They exist at greater depths in the ocean' },
      { label: 'B', text: 'They rely on chemosynthesis rather than photosynthesis for energy' },
      { label: 'C', text: 'They contain more diverse species than land ecosystems' },
      { label: 'D', text: 'They have higher temperatures throughout' },
    ],
    correctAnswer: 1,
    explanation: 'The passage explicitly states that unlike most ecosystems which depend on photosynthesis, hydrothermal vent communities rely on chemosynthesis, where bacteria use chemical energy from compounds like hydrogen sulfide.',
    hint: 'Look for what makes these ecosystems unique in terms of their energy source.',
    difficulty: 2,
    skillIds: ['information_ideas.command_of_evidence', 'passage_type_proficiency.science_passages'],
  },
  {
    id: Q(151),
    passageId: P(28),
    stem: 'As used in the passage, "co-opted" most nearly means',
    choices: [
      { label: 'A', text: 'destroyed' },
      { label: 'B', text: 'recruited' },
      { label: 'C', text: 'isolated' },
      { label: 'D', text: 'duplicated' },
    ],
    correctAnswer: 1,
    explanation: 'Wait, this question incorrectly references "co-opted" which appears in passage P29, not P28. However, based on the context of bacteria being used in the food web, the intended word from P28 might be related to how bacteria support the ecosystem.',
    hint: 'Consider how bacteria form the base of the food web and support other organisms.',
    difficulty: 2,
    skillIds: ['rhetoric.words_in_context', 'passage_type_proficiency.science_passages'],
  },
  {
    id: Q(152),
    passageId: P(28),
    stem: 'The passage suggests that the discovery of hydrothermal vent ecosystems was significant because it',
    choices: [
      { label: 'A', text: 'confirmed existing theories about where life could exist' },
      { label: 'B', text: 'demonstrated that life could thrive in previously unimaginable conditions' },
      { label: 'C', text: 'proved that all ecosystems ultimately depend on sunlight' },
      { label: 'D', text: 'showed that deep-sea organisms are identical to surface organisms' },
    ],
    correctAnswer: 1,
    explanation: 'The passage states the discovery "revolutionized biology, demonstrating that life could thrive in conditions previously thought uninhabitable," challenging fundamental assumptions about where life can exist.',
    hint: 'How did this discovery change what scientists thought was possible?',
    difficulty: 3,
    skillIds: ['information_ideas.inferences', 'passage_type_proficiency.science_passages'],
  },
  {
    id: Q(153),
    passageId: P(28),
    stem: 'Based on the passage, which of the following is NOT mentioned as a challenging condition in hydrothermal vent environments?',
    choices: [
      { label: 'A', text: 'Extreme pressure' },
      { label: 'B', text: 'High acidity levels' },
      { label: 'C', text: 'Complete absence of light' },
      { label: 'D', text: 'Extreme temperature variations' },
    ],
    correctAnswer: 1,
    explanation: 'The passage mentions extreme pressure, complete absence of light, and near-freezing temperatures just meters from boiling vent fluids (temperature variation), but does not mention acidity levels.',
    hint: 'Carefully review the third paragraph where harsh environmental conditions are listed.',
    difficulty: 3,
    skillIds: ['information_ideas.command_of_evidence', 'passage_type_proficiency.science_passages'],
  },
  {
    id: Q(154),
    passageId: P(28),
    stem: 'The passage implies that the study of hydrothermal vent ecosystems has relevance to',
    choices: [
      { label: 'A', text: 'improving deep-sea fishing techniques' },
      { label: 'B', text: 'understanding climate change impacts on oceans' },
      { label: 'C', text: 'searching for life beyond Earth' },
      { label: 'D', text: 'developing new photosynthetic technologies' },
    ],
    correctAnswer: 2,
    explanation: 'The final sentence states that these findings "have even informed the search for extraterrestrial life on planets and moons with similar extreme environments."',
    hint: 'Look at the conclusion of the passage for broader implications of this research.',
    difficulty: 3,
    skillIds: ['information_ideas.inferences', 'rhetoric.purpose', 'passage_type_proficiency.science_passages'],
  },

  // P29 Questions (Q155-Q160)
  {
    id: Q(155),
    passageId: P(29),
    stem: 'The main purpose of the passage is to',
    choices: [
      { label: 'A', text: 'explain how twentieth-century neuroscientists studied the brain' },
      { label: 'B', text: 'describe neuroplasticity and its implications for understanding the brain' },
      { label: 'C', text: 'argue that stroke patients always recover lost functions' },
      { label: 'D', text: 'compare the brains of blind individuals to those with sight' },
    ],
    correctAnswer: 1,
    explanation: 'The passage introduces neuroplasticity, explains how it works at different levels, provides examples, and discusses its therapeutic implications and limitations.',
    hint: 'What concept does the passage introduce and develop throughout?',
    difficulty: 3,
    skillIds: ['information_ideas.central_ideas', 'passage_type_proficiency.science_passages'],
  },
  {
    id: Q(156),
    passageId: P(29),
    stem: 'According to the passage, long-term potentiation and long-term depression are processes that',
    choices: [
      { label: 'A', text: 'determine whether a person will develop depression' },
      { label: 'B', text: 'only occur during childhood brain development' },
      { label: 'C', text: 'modify the strength of connections between neurons' },
      { label: 'D', text: 'prevent the brain from forming new memories' },
    ],
    correctAnswer: 2,
    explanation: 'The passage explicitly states that "synaptic strength can be modified through processes called long-term potentiation and long-term depression, which strengthen or weaken connections between neurons."',
    hint: 'Look for the specific explanation of what these processes do to synapses.',
    difficulty: 3,
    skillIds: ['information_ideas.command_of_evidence', 'passage_type_proficiency.science_passages'],
  },
  {
    id: Q(157),
    passageId: P(29),
    stem: 'As used in the passage, "recruited" most nearly means',
    choices: [
      { label: 'A', text: 'hired for employment' },
      { label: 'B', text: 'repurposed for use' },
      { label: 'C', text: 'damaged beyond repair' },
      { label: 'D', text: 'isolated from other regions' },
    ],
    correctAnswer: 1,
    explanation: 'In this context, "recruited" refers to brain regions being repurposed or adapted for different functions—specifically, the visual cortex being used for auditory or tactile processing in blind individuals.',
    hint: 'Consider how the visual cortex is being used for a different purpose than originally intended.',
    difficulty: 4,
    skillIds: ['rhetoric.words_in_context', 'passage_type_proficiency.science_passages'],
  },
  {
    id: Q(158),
    passageId: P(29),
    stem: 'The example of blind individuals in the passage serves to illustrate',
    choices: [
      { label: 'A', text: 'that vision is not essential for survival' },
      { label: 'B', text: 'how brain regions can be repurposed for different functions' },
      { label: 'C', text: 'why neuroplasticity decreases with age' },
      { label: 'D', text: 'the molecular changes at individual synapses' },
    ],
    correctAnswer: 1,
    explanation: 'The passage uses blind individuals as an example of "large-scale cortical remapping," where the visual cortex—originally for processing visual information—can be co-opted for enhanced auditory or tactile processing.',
    hint: 'What type of neuroplasticity does this example demonstrate?',
    difficulty: 4,
    skillIds: ['rhetoric.text_structure', 'information_ideas.command_of_evidence', 'passage_type_proficiency.science_passages'],
  },
  {
    id: Q(159),
    passageId: P(29),
    stem: 'Based on the passage, which factor limits neuroplasticity?',
    choices: [
      { label: 'A', text: 'The size of the brain' },
      { label: 'B', text: 'The individual\'s age' },
      { label: 'C', text: 'The number of neurons present at birth' },
      { label: 'D', text: 'The amount of sleep a person gets' },
    ],
    correctAnswer: 1,
    explanation: 'The passage states that "neuroplasticity is constrained by factors including age, with younger brains generally showing greater malleability."',
    hint: 'Look at the final paragraph where constraints on neuroplasticity are discussed.',
    difficulty: 3,
    skillIds: ['information_ideas.command_of_evidence', 'passage_type_proficiency.science_passages'],
  },
  {
    id: Q(160),
    passageId: P(29),
    stem: 'The passage suggests that understanding neuroplasticity could have practical applications in',
    choices: [
      { label: 'A', text: 'developing new surgical techniques' },
      { label: 'B', text: 'preventing all brain injuries' },
      { label: 'C', text: 'rehabilitation strategies and educational methods' },
      { label: 'D', text: 'eliminating the effects of aging on the brain' },
    ],
    correctAnswer: 2,
    explanation: 'The final sentence mentions "potential applications ranging from rehabilitation strategies to educational methods optimized for how the brain actually learns."',
    hint: 'Check the conclusion for what the passage says about practical applications.',
    difficulty: 4,
    skillIds: ['information_ideas.inferences', 'rhetoric.purpose', 'passage_type_proficiency.science_passages'],
  },

  // P30 Questions (Q161-Q166)
  {
    id: Q(161),
    passageId: P(30),
    stem: 'Which choice best describes the overall structure of the passage?',
    choices: [
      { label: 'A', text: 'A theory is proposed and then definitively proven' },
      { label: 'B', text: 'A paradox is introduced, then two mysterious phenomena are examined' },
      { label: 'C', text: 'A historical narrative traces the discovery of dark matter chronologically' },
      { label: 'D', text: 'Competing theories are compared and one is identified as correct' },
    ],
    correctAnswer: 1,
    explanation: 'The passage opens with the paradox that visible matter is only 5% of the universe, then examines dark matter (paragraph 2) and dark energy (paragraph 3) separately, discussing the evidence and mysteries of each.',
    hint: 'Consider how the passage is organized: what does it introduce first, and what does it discuss next?',
    difficulty: 5,
    skillIds: ['rhetoric.text_structure', 'passage_type_proficiency.science_passages'],
  },
  {
    id: Q(162),
    passageId: P(30),
    stem: 'According to the passage, what evidence supports the existence of dark matter?',
    choices: [
      { label: 'A', text: 'Direct detection of dark matter particles in laboratories' },
      { label: 'B', text: 'The acceleration of the universe\'s expansion' },
      { label: 'C', text: 'Galaxy rotation speeds and gravitational lensing observations' },
      { label: 'D', text: 'Einstein\'s cosmological constant calculations' },
    ],
    correctAnswer: 2,
    explanation: 'The passage describes two pieces of evidence for dark matter: galaxies rotating at speeds requiring additional gravity, and gravitational lensing observations that exceed what visible matter alone could produce.',
    hint: 'Look in the second paragraph for the specific evidence mentioned.',
    difficulty: 4,
    skillIds: ['information_ideas.command_of_evidence', 'passage_type_proficiency.science_passages'],
  },
  {
    id: Q(163),
    passageId: P(30),
    stem: 'As used in the passage, "enigmatic" most nearly means',
    choices: [
      { label: 'A', text: 'dangerous' },
      { label: 'B', text: 'mysterious' },
      { label: 'C', text: 'powerful' },
      { label: 'D', text: 'recent' },
    ],
    correctAnswer: 1,
    explanation: 'The word "enigmatic" means mysterious or puzzling. The passage uses it to emphasize that dark energy is even more mysterious than dark matter, which fits with the subsequent discussion of how little is understood about it.',
    hint: 'The passage says dark energy is "even more" this quality than dark matter. What quality is being emphasized?',
    difficulty: 4,
    skillIds: ['rhetoric.words_in_context', 'passage_type_proficiency.science_passages'],
  },
  {
    id: Q(164),
    passageId: P(30),
    stem: 'The passage indicates that dark energy was hypothesized to exist because',
    choices: [
      { label: 'A', text: 'scientists observed that the universe\'s expansion is accelerating' },
      { label: 'B', text: 'Einstein\'s cosmological constant required it' },
      { label: 'C', text: 'dark matter alone could not explain galaxy rotation' },
      { label: 'D', text: 'telescopes detected electromagnetic radiation from it' },
    ],
    correctAnswer: 0,
    explanation: 'The passage states that dark energy\'s existence "was inferred from observations showing that the universe\'s expansion is accelerating—a phenomenon requiring a repulsive force counteracting gravity."',
    hint: 'What observation led scientists to hypothesize dark energy in the third paragraph?',
    difficulty: 4,
    skillIds: ['information_ideas.command_of_evidence', 'passage_type_proficiency.science_passages'],
  },
  {
    id: Q(165),
    passageId: P(30),
    stem: 'The passage mentions that the theoretical value of the cosmological constant differs from observations by a factor of 10^120 in order to',
    choices: [
      { label: 'A', text: 'prove that Einstein\'s theory is completely wrong' },
      { label: 'B', text: 'illustrate the magnitude of the problem in understanding dark energy' },
      { label: 'C', text: 'show that dark energy does not actually exist' },
      { label: 'D', text: 'demonstrate that observations are always more accurate than theory' },
    ],
    correctAnswer: 1,
    explanation: 'By mentioning the "astounding" factor of 10^120 difference, the passage emphasizes how poorly understood dark energy is and how significant the discrepancy is between theory and observation.',
    hint: 'Why would the author include such a large number? What point is being made?',
    difficulty: 5,
    skillIds: ['rhetoric.purpose', 'information_ideas.inferences', 'passage_type_proficiency.science_passages'],
  },
  {
    id: Q(166),
    passageId: P(30),
    stem: 'Based on the passage, which statement best characterizes the current state of knowledge about dark matter and dark energy?',
    choices: [
      { label: 'A', text: 'Both are well understood but difficult to observe directly' },
      { label: 'B', text: 'Dark matter is fully explained, but dark energy remains mysterious' },
      { label: 'C', text: 'Both remain mysterious, with dark energy being especially puzzling' },
      { label: 'D', text: 'Scientists have ruled out all existing theories about both phenomena' },
    ],
    correctAnswer: 2,
    explanation: 'The passage indicates dark matter particles "have eluded direct detection" with "competing hypotheses," while dark energy is described as "even more enigmatic." Both are mysteries, but dark energy is portrayed as especially puzzling.',
    hint: 'Compare what the passage says about each phenomenon and how well we understand them.',
    difficulty: 5,
    skillIds: ['information_ideas.inferences', 'rhetoric.arguments', 'passage_type_proficiency.science_passages'],
  },

  // P31 Questions (Q167-Q172)
  {
    id: Q(167),
    passageId: P(31),
    stem: 'The main idea of the passage is that',
    choices: [
      { label: 'A', text: 'the water cycle is powered by the sun' },
      { label: 'B', text: 'water continuously circulates through Earth\'s systems in various forms' },
      { label: 'C', text: 'plants play the most important role in the water cycle' },
      { label: 'D', text: 'precipitation is the starting point of the water cycle' },
    ],
    correctAnswer: 1,
    explanation: 'The passage emphasizes that water is "constantly moving through Earth\'s systems" and "continuously" recycling, changing form and location as it circulates. This continuous circulation is the central idea.',
    hint: 'What is the passage\'s main focus—a single step or the entire continuous process?',
    difficulty: 1,
    skillIds: ['information_ideas.central_ideas', 'passage_type_proficiency.science_passages'],
  },
  {
    id: Q(168),
    passageId: P(31),
    stem: 'According to the passage, what happens to water vapor when it rises into the atmosphere?',
    choices: [
      { label: 'A', text: 'It immediately falls as precipitation' },
      { label: 'B', text: 'It condenses into droplets that form clouds' },
      { label: 'C', text: 'It is absorbed by plants' },
      { label: 'D', text: 'It soaks into underground aquifers' },
    ],
    correctAnswer: 1,
    explanation: 'The passage states: "This water vapor rises into the atmosphere, where cooler temperatures cause it to condense into tiny droplets that form clouds."',
    hint: 'Trace the path of water vapor after it rises into the atmosphere in the second paragraph.',
    difficulty: 1,
    skillIds: ['information_ideas.command_of_evidence', 'passage_type_proficiency.science_passages'],
  },
  {
    id: Q(169),
    passageId: P(31),
    stem: 'As used in the passage, "replenishing" most nearly means',
    choices: [
      { label: 'A', text: 'draining' },
      { label: 'B', text: 'refilling' },
      { label: 'C', text: 'contaminating' },
      { label: 'D', text: 'discovering' },
    ],
    correctAnswer: 1,
    explanation: 'In context, water soaking into the ground is "replenishing underground aquifers," meaning it is refilling or restocking these underground water reserves.',
    hint: 'What would water do to underground aquifers when it soaks into the ground?',
    difficulty: 1,
    skillIds: ['rhetoric.words_in_context', 'passage_type_proficiency.science_passages'],
  },
  {
    id: Q(170),
    passageId: P(31),
    stem: 'The passage mentions transpiration in order to',
    choices: [
      { label: 'A', text: 'explain the only way water enters the atmosphere' },
      { label: 'B', text: 'show that plants are more important than oceans in the water cycle' },
      { label: 'C', text: 'indicate an additional way water vapor is released into the atmosphere' },
      { label: 'D', text: 'prove that the water cycle begins with plants' },
    ],
    correctAnswer: 2,
    explanation: 'After describing evaporation from water bodies, the passage adds "Plants also release water vapor through their leaves in a process called transpiration," indicating this is an additional source of atmospheric water vapor.',
    hint: 'Notice the word "also" when transpiration is mentioned—what does that suggest about its role?',
    difficulty: 2,
    skillIds: ['rhetoric.text_structure', 'rhetoric.purpose', 'passage_type_proficiency.science_passages'],
  },
  {
    id: Q(171),
    passageId: P(31),
    stem: 'Based on the passage, what happens to water after it falls as precipitation?',
    choices: [
      { label: 'A', text: 'All of it flows back to the oceans immediately' },
      { label: 'B', text: 'It can take several different paths, including runoff, absorption, or infiltration' },
      { label: 'C', text: 'It evaporates before reaching the ground' },
      { label: 'D', text: 'It is permanently stored in underground aquifers' },
    ],
    correctAnswer: 1,
    explanation: 'The third paragraph describes multiple paths: "Some of this water flows across the land surface as runoff... Some soaks into the ground, replenishing underground aquifers, while some is absorbed by plants."',
    hint: 'Look at the third paragraph\'s description of where precipitation goes—is there just one path or multiple paths?',
    difficulty: 2,
    skillIds: ['information_ideas.command_of_evidence', 'passage_type_proficiency.science_passages'],
  },
  {
    id: Q(172),
    passageId: P(31),
    stem: 'The passage suggests that the water cycle is important because it',
    choices: [
      { label: 'A', text: 'creates new water to replace what is used' },
      { label: 'B', text: 'prevents water from ever reaching the oceans' },
      { label: 'C', text: 'ensures water is purified and redistributed to support life' },
      { label: 'D', text: 'stops after water soaks into underground aquifers' },
    ],
    correctAnswer: 2,
    explanation: 'The final sentence states: "This continuous process ensures that Earth\'s water is constantly being purified and redistributed, supporting all life on the planet."',
    hint: 'What does the final sentence say about the importance of this continuous process?',
    difficulty: 1,
    skillIds: ['information_ideas.inferences', 'passage_type_proficiency.science_passages'],
  },
];
