import { PassageType } from '../entities/passage.entity';

const P = (n: number) => `00000000-0000-0000-0000-${n.toString().padStart(12, '0')}`;
const Q = (n: number) => `10000000-0000-0000-0000-${n.toString().padStart(12, '0')}`;

export const literaturePassages = [
  {
    id: P(17),
    title: 'The Summer of Jazz',
    type: PassageType.LITERATURE,
    difficulty: 2,
    source: 'Adapted from a contemporary short story collection',
    text: `Maya hadn't expected much from her grandfather's old record player, a dusty relic she'd found while cleaning out the attic. But when she placed the needle on a scratched vinyl labeled "Miles Davis - Kind of Blue," something shifted inside her. The trumpet's melancholy notes seemed to unlock a language she'd been searching for without knowing it.

For weeks, she returned to that attic, working her way through her grandfather's collection. Each album was a portal: Coltrane taught her about relentless pursuit, Billie Holiday about vulnerability as strength, Monk about finding beauty in the unexpected. Her friends didn't understand why she'd abandoned her earbuds for this ancient technology, why she spent hours decoding liner notes written decades before her birth.

At school, Maya felt increasingly disconnected from conversations about trending songs and viral dance challenges. Yet in the attic, surrounded by cardboard album sleeves and the warm crackle of vinyl, she felt more connected than ever—to her grandfather, to history, to something larger than her suburban teenage life. The music asked questions rather than providing easy answers, and Maya found herself thinking differently about everything.`,
    wordCount: 200,
    reviewStatus: 'approved',
  },
  {
    id: P(18),
    title: 'Between Two Worlds',
    type: PassageType.LITERATURE,
    difficulty: 3,
    source: 'Adapted from an immigrant memoir',
    text: `At the immigration office, Elena practiced her new name under her breath—"Helen"—the way the school counselor had suggested. It felt like wearing someone else's coat, slightly too large in the shoulders. Her mother, sitting beside her with a folded handkerchief in her lap, whispered firmly in their native tongue: "You are Elena. Don't forget."

But forgetting, Elena had learned, was sometimes a form of survival. She'd already forgotten how to spell certain words in her first language, forgotten the exact melody of her grandmother's lullabies. At school, she perfected an American accent, laughing at jokes she didn't quite understand, nodding along to references that sailed past her like ships in fog.

The translation happened in both directions. At home, she translated American customs to her bewildered parents—why teachers wanted them to call instead of visiting in person, why she needed fifty dollars for a "homecoming" that had nothing to do with actually coming home. Each translation felt like a small betrayal, as if she were slowly erasing one world to make room for another. Yet there were moments—helping her father read his medication labels, seeing her mother's face light up when Elena explained a joke—when Elena glimpsed a third possibility: not choosing between worlds, but building a bridge.`,
    wordCount: 210,
    reviewStatus: 'approved',
  },
  {
    id: P(19),
    title: 'The Gallery Opening',
    type: PassageType.LITERATURE,
    difficulty: 4,
    source: 'Adapted from a contemporary novel about artists',
    text: `Standing before her own paintings at the gallery opening, Margaret felt like an anthropologist studying artifacts from someone else's life. The crowds murmured appreciatively, champagne glasses tilting in the track lighting, while she recognized none of the passion that had driven her to create these works thirty years ago. Success had arrived late, as it often does in the arts—too late, she sometimes thought, to mean what it should have meant.

The younger artists treated her with careful deference, soliciting her opinions like pilgrims seeking wisdom from an oracle. But Margaret remembered herself at their age: fierce, hungry, painting not for galleries but because not painting felt like suffocation. She'd worked night shifts at a diner, mixed her own pigments to save money, pinned rejection letters to her studio wall as fuel. Those paintings—raw, uncompromising, technically flawed—hung in no museums. They'd been painted over or abandoned in storage units when she couldn't pay rent.

These new canvases, the ones currently fetching five figures, were accomplished but safe. She'd learned what collectors wanted, what critics praised, what fit the narrative of her career. The irony wasn't lost on her: she'd finally mastered her craft just as the fire that made mastery matter had dimmed to embers. The gallery owner touched her elbow, steering her toward a collector, and Margaret smiled her practiced smile, playing the role of the artist she'd become rather than the one she'd been.`,
    wordCount: 230,
    reviewStatus: 'approved',
  },
  {
    id: P(20),
    title: 'Palimpsest',
    type: PassageType.LITERATURE,
    difficulty: 5,
    source: 'Adapted from an experimental fiction anthology',
    text: `The morning you forget your daughter's name, you're stirring coffee—three spoons of sugar, the way you've always taken it, except perhaps you haven't, perhaps that's her preference bleeding into your memory like watercolor on wet paper. The spoon circles, circles, a whirlpool pulling you back to other kitchens, other mornings, until you can't distinguish which life you're remembering and which you're currently living.

She stands in the doorway (or is it you standing, watching yourself?) and you know her by feel rather than by name—the way you know your own hand in the dark. This should terrify you. Instead, there's relief in the dissolution of certainty, the way ice surrenders to water surrenders to vapor. Identity, you're learning, is just insistence, the stubborn repetition of "I am, I am, I am" until the words wear grooves in your consciousness deep enough to mistake for truth.

You try to explain this to the doctor, but linear narrative requires a narrator, and you're not sure there's anyone home to narrate. There are only these fragments: taste of burnt toast, weight of her hand on your shoulder, afternoon light the color of honey. Maybe identity was never about continuity but about these disconnected moments that briefly flare with recognition. Maybe you're not losing yourself but discovering that there was never a self to lose, only this procession of instants pretending to be a life.`,
    wordCount: 238,
    reviewStatus: 'approved',
  },
  {
    id: P(21),
    title: 'The Swim Meet',
    type: PassageType.LITERATURE,
    difficulty: 2,
    source: 'Adapted from a young adult fiction collection',
    text: `Jenna had always been faster than me in the water. Since we were eight, racing across our neighborhood pool, she'd beaten me by at least a body length every time. I didn't mind—we were best friends, and her victories felt partly mine. We trained together, shared lanes, compared split times, dreamed together about making varsity.

But this year, something changed. My coach adjusted my flip turns, and suddenly I was shaving seconds off my freestyle. At practice, I began touching the wall first, then first by wider margins. I'd glance back to find Jenna's face unreadable behind her goggles, her congratulations feeling increasingly mechanical.

The morning of the championship meet, I found a text from her: "Good luck today. You'll be great." No mention of her own races, no suggestion we meet early to warm up together like we always did. At the pool, she was polite but distant, stretching alone in a corner. When they called our heat for the 200-meter freestyle, we stood on adjacent blocks for the first time as competitors rather than teammates. I wanted to reach over and say something, anything to bridge the sudden gulf between us. But the starting buzzer sounded, and we dove into our separate lanes, the water swallowing whatever words I might have found.`,
    wordCount: 218,
    reviewStatus: 'approved',
  },
];

export const literatureQuestions = [
  // P17: The Summer of Jazz (Q83-Q88)
  {
    id: Q(83),
    passageId: P(17),
    stem: 'Which choice best describes the main idea of the passage?',
    choices: [
      { label: 'A', text: 'A teenager discovers her passion for jazz music and develops a deeper connection to her family history.' },
      { label: 'B', text: 'A young woman learns to appreciate antique technology despite her friends\' disapproval.' },
      { label: 'C', text: 'A student struggles to balance her interest in vintage music with her social life at school.' },
      { label: 'D', text: 'A granddaughter fulfills her grandfather\'s wish by preserving his record collection.' },
    ],
    correctAnswer: 0,
    explanation: 'The passage centers on Maya\'s discovery of jazz through her grandfather\'s records and how this music creates a meaningful connection to her grandfather, history, and something larger than her everyday life. While social disconnection is mentioned, it\'s secondary to her primary journey of discovery and connection.',
    hint: 'Focus on what Maya gains from the experience rather than what she loses or struggles with.',
    difficulty: 2,
    skillIds: ['information_ideas.central_ideas', 'passage_type_proficiency.literature_passages'],
  },
  {
    id: Q(84),
    passageId: P(17),
    stem: 'As used in the passage, "portal" most nearly means',
    choices: [
      { label: 'A', text: 'doorway.' },
      { label: 'B', text: 'gateway to understanding.' },
      { label: 'C', text: 'website.' },
      { label: 'D', text: 'musical composition.' },
    ],
    correctAnswer: 1,
    explanation: 'In context, each album serving as a "portal" refers to how the music provides access to different perspectives and lessons (Coltrane teaching pursuit, Holiday teaching vulnerability). This metaphorical use means "gateway to understanding" rather than a literal doorway.',
    hint: 'Consider how the albums function for Maya—what do they provide access to?',
    difficulty: 2,
    skillIds: ['rhetoric.words_in_context', 'passage_type_proficiency.literature_passages'],
  },
  {
    id: Q(85),
    passageId: P(17),
    stem: 'The passage most strongly suggests that Maya\'s friends',
    choices: [
      { label: 'A', text: 'actively discourage her interest in jazz music.' },
      { label: 'B', text: 'do not share or understand her newfound passion.' },
      { label: 'C', text: 'prefer classical music to contemporary genres.' },
      { label: 'D', text: 'have similar interests in vintage technology.' },
    ],
    correctAnswer: 1,
    explanation: 'The passage states that "Her friends didn\'t understand why she\'d abandoned her earbuds for this ancient technology." This indicates a lack of understanding rather than active discouragement, and their interests lie in "trending songs and viral dance challenges" rather than her vintage jazz.',
    hint: 'Look for what the text explicitly states about the friends\' reaction to Maya\'s interest.',
    difficulty: 3,
    skillIds: ['information_ideas.inferences', 'passage_type_proficiency.literature_passages'],
  },
  {
    id: Q(86),
    passageId: P(17),
    stem: 'The author uses the phrase "warm crackle of vinyl" primarily to',
    choices: [
      { label: 'A', text: 'emphasize the poor quality of old recording technology.' },
      { label: 'B', text: 'suggest the comforting, authentic quality of Maya\'s experience.' },
      { label: 'C', text: 'illustrate why Maya\'s friends prefer modern music formats.' },
      { label: 'D', text: 'indicate that the records are damaged and need replacement.' },
    ],
    correctAnswer: 1,
    explanation: 'The word "warm" combined with "crackle" creates positive sensory imagery that emphasizes the comforting, authentic quality of the vinyl experience. This description appears in a sentence about Maya feeling "more connected than ever," reinforcing the positive associations.',
    hint: 'Pay attention to the descriptive word paired with "crackle" and the context in which this phrase appears.',
    difficulty: 3,
    skillIds: ['rhetoric.purpose', 'passage_type_proficiency.literature_passages'],
  },
  {
    id: Q(87),
    passageId: P(17),
    stem: 'Which statement best describes the contrast presented in the final paragraph?',
    choices: [
      { label: 'A', text: 'Old music versus new music' },
      { label: 'B', text: 'Social disconnection versus meaningful connection' },
      { label: 'C', text: 'Digital technology versus analog technology' },
      { label: 'D', text: 'Easy answers versus difficult questions' },
    ],
    correctAnswer: 1,
    explanation: 'The final paragraph explicitly contrasts feeling "increasingly disconnected from conversations" at school with feeling "more connected than ever" in the attic. This juxtaposition of social disconnection versus meaningful connection is the central contrast of the paragraph.',
    hint: 'Identify what Maya loses and what she gains, as described in the final paragraph.',
    difficulty: 2,
    skillIds: ['rhetoric.text_structure', 'passage_type_proficiency.literature_passages'],
  },
  {
    id: Q(88),
    passageId: P(17),
    stem: 'The passage suggests that Maya values the jazz music primarily because it',
    choices: [
      { label: 'A', text: 'helps her excel in her music classes at school.' },
      { label: 'B', text: 'makes her feel superior to her peers who listen to popular music.' },
      { label: 'C', text: 'offers complexity and encourages deeper thinking.' },
      { label: 'D', text: 'reminds her of happy memories with her grandfather.' },
    ],
    correctAnswer: 2,
    explanation: 'The passage concludes by noting that "The music asked questions rather than providing easy answers, and Maya found herself thinking differently about everything." This directly indicates she values the music for its intellectual and philosophical complexity, not for school performance or social superiority.',
    hint: 'Look at the final sentence for explicit evidence about what Maya values in the music.',
    difficulty: 3,
    skillIds: ['information_ideas.command_of_evidence', 'passage_type_proficiency.literature_passages'],
  },

  // P18: Between Two Worlds (Q89-Q94)
  {
    id: Q(89),
    passageId: P(18),
    stem: 'The central theme of the passage is best described as',
    choices: [
      { label: 'A', text: 'the difficulty of learning English as a second language.' },
      { label: 'B', text: 'the tension between preserving cultural identity and assimilating to a new culture.' },
      { label: 'C', text: 'the conflict between immigrant parents and their Americanized children.' },
      { label: 'D', text: 'the challenges of navigating the American immigration system.' },
    ],
    correctAnswer: 1,
    explanation: 'The passage explores Elena\'s struggle between her original identity (Elena) and her adopted one (Helen), between her native culture and American customs. The final sentence explicitly introduces the possibility of "not choosing between worlds, but building a bridge," which crystallizes this central tension.',
    hint: 'Consider what Elena is struggling with throughout the passage and what resolution she glimpses at the end.',
    difficulty: 3,
    skillIds: ['information_ideas.central_ideas', 'passage_type_proficiency.literature_passages'],
  },
  {
    id: Q(90),
    passageId: P(18),
    stem: 'As used in the passage, "betrayal" most nearly means',
    choices: [
      { label: 'A', text: 'an act of disloyalty or treachery.' },
      { label: 'B', text: 'a violation of trust.' },
      { label: 'C', text: 'an abandonment of her heritage.' },
      { label: 'D', text: 'a criminal offense.' },
    ],
    correctAnswer: 2,
    explanation: 'In context, Elena feels each translation is "a small betrayal, as if she were slowly erasing one world to make room for another." This specifically refers to abandoning or erasing her original culture, making "abandonment of her heritage" the most precise meaning in this context.',
    hint: 'Look at what immediately follows the word "betrayal"—the passage explains what Elena feels she is betraying.',
    difficulty: 3,
    skillIds: ['rhetoric.words_in_context', 'passage_type_proficiency.literature_passages'],
  },
  {
    id: Q(91),
    passageId: P(18),
    stem: 'The passage most strongly suggests that Elena\'s mother',
    choices: [
      { label: 'A', text: 'opposes Elena\'s attempts to adapt to American culture.' },
      { label: 'B', text: 'wants Elena to maintain her connection to her original identity.' },
      { label: 'C', text: 'refuses to learn English or American customs.' },
      { label: 'D', text: 'regrets immigrating to the United States.' },
    ],
    correctAnswer: 1,
    explanation: 'The mother\'s whispered insistence, "You are Elena. Don\'t forget," shows her desire for her daughter to maintain her original identity. The passage doesn\'t suggest she opposes all adaptation (choice A is too strong) or that she regrets immigration, just that she wants Elena to remember who she is.',
    hint: 'Focus on what the mother actually says and what it reveals about her values.',
    difficulty: 2,
    skillIds: ['information_ideas.inferences', 'passage_type_proficiency.literature_passages'],
  },
  {
    id: Q(92),
    passageId: P(18),
    stem: 'The author uses the simile "like ships in fog" to',
    choices: [
      { label: 'A', text: 'suggest that Elena is confused about maritime terminology.' },
      { label: 'B', text: 'emphasize how cultural references pass by Elena without her fully grasping them.' },
      { label: 'C', text: 'indicate that Elena is interested in naval history.' },
      { label: 'D', text: 'show that Elena\'s English comprehension is improving.' },
    ],
    correctAnswer: 1,
    explanation: 'The simile describes references "that sailed past her like ships in fog," creating an image of things moving by without clear visibility or understanding. This effectively conveys how Elena doesn\'t fully grasp the cultural references her classmates make.',
    hint: 'Visualize what ships in fog would look like and how this relates to Elena\'s experience with cultural references.',
    difficulty: 2,
    skillIds: ['rhetoric.purpose', 'passage_type_proficiency.literature_passages'],
  },
  {
    id: Q(93),
    passageId: P(18),
    stem: 'Which choice best describes the structure of the passage?',
    choices: [
      { label: 'A', text: 'A chronological account of Elena\'s first year in America' },
      { label: 'B', text: 'A comparison between Elena\'s life in two different countries' },
      { label: 'C', text: 'An exploration of Elena\'s internal conflict followed by a potential resolution' },
      { label: 'D', text: 'A description of various challenges faced by immigrant families' },
    ],
    correctAnswer: 2,
    explanation: 'The passage first explores Elena\'s struggle with dual identities and the tension between cultures (paragraphs 1-3), then concludes with her glimpsing "a third possibility: not choosing between worlds, but building a bridge"—a potential resolution to her internal conflict.',
    hint: 'Notice how the passage moves from describing a problem to suggesting a possible solution.',
    difficulty: 4,
    skillIds: ['rhetoric.text_structure', 'passage_type_proficiency.literature_passages'],
  },
  {
    id: Q(94),
    passageId: P(18),
    stem: 'The passage indicates that Elena\'s role as translator for her parents makes her feel conflicted because',
    choices: [
      { label: 'A', text: 'she lacks the vocabulary needed for accurate translation.' },
      { label: 'B', text: 'her parents criticize her translations as inadequate.' },
      { label: 'C', text: 'translating feels like erasing one culture to accommodate another.' },
      { label: 'D', text: 'she resents having to help her parents with basic tasks.' },
    ],
    correctAnswer: 2,
    explanation: 'The passage explicitly states that "Each translation felt like a small betrayal, as if she were slowly erasing one world to make room for another." This directly explains her conflicted feelings about translating—it\'s not about ability or resentment, but about the cultural implications of the act.',
    hint: 'The passage directly explains why translation feels problematic to Elena. Look for explicit textual evidence.',
    difficulty: 2,
    skillIds: ['information_ideas.command_of_evidence', 'passage_type_proficiency.literature_passages'],
  },

  // P19: The Gallery Opening (Q95-Q100)
  {
    id: Q(95),
    passageId: P(19),
    stem: 'The main purpose of the passage is to',
    choices: [
      { label: 'A', text: 'celebrate an artist\'s long-awaited recognition and success.' },
      { label: 'B', text: 'critique the commercial art world and its superficial values.' },
      { label: 'C', text: 'explore the tension between artistic passion and commercial success.' },
      { label: 'D', text: 'encourage young artists to persevere despite early failures.' },
    ],
    correctAnswer: 2,
    explanation: 'The passage centers on Margaret\'s realization that her current successful paintings lack the passion of her earlier, unsuccessful work. The irony of achieving technical mastery and recognition just as "the fire that made mastery matter had dimmed to embers" captures this tension between passion and commercial success.',
    hint: 'Consider what Margaret has gained and what she feels she has lost.',
    difficulty: 3,
    skillIds: ['rhetoric.purpose', 'passage_type_proficiency.literature_passages'],
  },
  {
    id: Q(96),
    passageId: P(19),
    stem: 'As used in the passage, "oracle" most nearly means',
    choices: [
      { label: 'A', text: 'a computer database system.' },
      { label: 'B', text: 'a mysterious prophet.' },
      { label: 'C', text: 'a source of wise guidance.' },
      { label: 'D', text: 'an ancient religious site.' },
    ],
    correctAnswer: 2,
    explanation: 'Younger artists treat Margaret with "careful deference, soliciting her opinions like pilgrims seeking wisdom from an oracle." In this context, oracle refers to a source of wisdom and guidance, not a database, and while oracles were prophets, "source of wise guidance" most precisely captures the functional meaning here.',
    hint: 'Consider what the younger artists are seeking from Margaret when they treat her like an oracle.',
    difficulty: 3,
    skillIds: ['rhetoric.words_in_context', 'passage_type_proficiency.literature_passages'],
  },
  {
    id: Q(97),
    passageId: P(19),
    stem: 'The passage most strongly suggests that Margaret\'s earlier paintings were',
    choices: [
      { label: 'A', text: 'technically superior but less emotionally compelling than her current work.' },
      { label: 'B', text: 'financially successful but critically dismissed.' },
      { label: 'C', text: 'passionate and uncompromising but commercially unsuccessful.' },
      { label: 'D', text: 'carefully designed to please art collectors and critics.' },
    ],
    correctAnswer: 2,
    explanation: 'Margaret describes her younger self as "fierce, hungry, painting not for galleries but because not painting felt like suffocation." These paintings were "raw, uncompromising, technically flawed" and "hung in no museums"—they were passionate and genuine but commercially unsuccessful, unlike her current safe, marketable work.',
    hint: 'Compare what the passage says about Margaret\'s early paintings to her current ones.',
    difficulty: 4,
    skillIds: ['information_ideas.inferences', 'passage_type_proficiency.literature_passages'],
  },
  {
    id: Q(98),
    passageId: P(19),
    stem: 'The author\'s use of the phrase "playing the role of the artist she\'d become rather than the one she\'d been" suggests that Margaret',
    choices: [
      { label: 'A', text: 'has become dishonest about her artistic process.' },
      { label: 'B', text: 'views her current artistic identity as a performance rather than authentic expression.' },
      { label: 'C', text: 'regrets changing her painting style over the years.' },
      { label: 'D', text: 'prefers her current identity to her past self.' },
    ],
    correctAnswer: 1,
    explanation: 'The phrase "playing the role" implies performance and inauthenticity. Contrasting "the artist she\'d become" with "the one she\'d been" emphasizes that Margaret sees her current identity as something she performs rather than genuinely embodies, unlike her passionate earlier self.',
    hint: 'What does "playing the role" suggest about authenticity versus performance?',
    difficulty: 4,
    skillIds: ['rhetoric.purpose', 'passage_type_proficiency.literature_passages'],
  },
  {
    id: Q(99),
    passageId: P(19),
    stem: 'Which statement best describes the irony presented in the passage?',
    choices: [
      { label: 'A', text: 'Margaret achieves recognition only after her work becomes less personally meaningful.' },
      { label: 'B', text: 'Younger artists respect Margaret despite her technical limitations.' },
      { label: 'C', text: 'Art collectors prefer Margaret\'s weaker paintings to her stronger ones.' },
      { label: 'D', text: 'Margaret\'s early financial struggles made her a better artist.' },
    ],
    correctAnswer: 0,
    explanation: 'The passage explicitly states the irony: "she\'d finally mastered her craft just as the fire that made mastery matter had dimmed to embers." Margaret achieves commercial success and technical skill precisely when her work has lost the passion and authenticity that initially drove her to create.',
    hint: 'The passage directly identifies an irony in the third paragraph. What is the timing mismatch?',
    difficulty: 3,
    skillIds: ['information_ideas.central_ideas', 'passage_type_proficiency.literature_passages'],
  },
  {
    id: Q(100),
    passageId: P(19),
    stem: 'The detail about Margaret\'s rejection letters being "pinned to her studio wall as fuel" serves primarily to',
    choices: [
      { label: 'A', text: 'illustrate her bitterness toward critics who dismissed her early work.' },
      { label: 'B', text: 'demonstrate her determination and defiant attitude as a young artist.' },
      { label: 'C', text: 'suggest she was motivated primarily by a desire to prove others wrong.' },
      { label: 'D', text: 'show that she kept poor records of her artistic submissions.' },
    ],
    correctAnswer: 1,
    explanation: 'Using rejection letters "as fuel" demonstrates how she transformed rejection into motivation, showing determination and defiance. This detail appears in a section contrasting her fierce, hungry younger self with her current safer approach, emphasizing her earlier passionate, uncompromising attitude.',
    hint: 'Think about what using rejection letters "as fuel" reveals about her mindset and character.',
    difficulty: 4,
    skillIds: ['information_ideas.command_of_evidence', 'passage_type_proficiency.literature_passages'],
  },

  // P20: Palimpsest (Q101-Q106)
  {
    id: Q(101),
    passageId: P(20),
    stem: 'The primary purpose of the passage is to',
    choices: [
      { label: 'A', text: 'describe the medical symptoms of dementia from a patient\'s perspective.' },
      { label: 'B', text: 'explore philosophical questions about memory, identity, and the nature of self.' },
      { label: 'C', text: 'argue that personal identity is an illusion created by language.' },
      { label: 'D', text: 'illustrate the emotional impact of memory loss on family relationships.' },
    ],
    correctAnswer: 1,
    explanation: 'While the passage involves memory loss, its primary focus is philosophical rather than medical or emotional. It explores questions like whether identity requires continuity, whether there is a stable "self," and whether we are "just these disconnected moments." The experimental, meditative style emphasizes philosophical inquiry.',
    hint: 'Consider the overall tone and what questions the passage raises rather than what story it tells.',
    difficulty: 5,
    skillIds: ['rhetoric.purpose', 'passage_type_proficiency.literature_passages'],
  },
  {
    id: Q(102),
    passageId: P(20),
    stem: 'As used in the passage, "palimpsest" in the title most likely refers to',
    choices: [
      { label: 'A', text: 'a medical term for memory deterioration.' },
      { label: 'B', text: 'a manuscript that has been written over, leaving traces of earlier text.' },
      { label: 'C', text: 'a type of psychological therapy for dementia patients.' },
      { label: 'D', text: 'a philosophical concept about the nature of time.' },
    ],
    correctAnswer: 1,
    explanation: 'A palimpsest is a manuscript that has been written over, with earlier text still partially visible beneath new writing. This metaphor perfectly captures the narrator\'s experience of memories bleeding into each other ("her preference bleeding into your memory like watercolor on wet paper") and identities layering over one another.',
    hint: 'Think about how the narrator describes memories overlapping and bleeding together. What writing surface would show similar layering?',
    difficulty: 5,
    skillIds: ['rhetoric.words_in_context', 'information_ideas.inferences', 'passage_type_proficiency.literature_passages'],
  },
  {
    id: Q(103),
    passageId: P(20),
    stem: 'The narrator\'s statement that "identity, you\'re learning, is just insistence" suggests that',
    choices: [
      { label: 'A', text: 'maintaining a sense of self requires conscious, repeated effort.' },
      { label: 'B', text: 'people with strong personalities are more resistant to memory loss.' },
      { label: 'C', text: 'the narrator has become stubborn due to the illness.' },
      { label: 'D', text: 'identity is something doctors insist patients must maintain.' },
    ],
    correctAnswer: 0,
    explanation: 'The passage describes identity as "the stubborn repetition of \'I am, I am, I am\' until the words wear grooves in your consciousness deep enough to mistake for truth." This suggests identity is created and maintained through persistent, conscious repetition rather than being an inherent, stable thing.',
    hint: 'Look at what immediately follows this statement—the passage explains what "insistence" means in this context.',
    difficulty: 5,
    skillIds: ['information_ideas.inferences', 'passage_type_proficiency.literature_passages'],
  },
  {
    id: Q(104),
    passageId: P(20),
    stem: 'The passage\'s use of second-person narration ("you") primarily serves to',
    choices: [
      { label: 'A', text: 'create emotional distance from a painful experience.' },
      { label: 'B', text: 'directly accuse the reader of forgetting loved ones.' },
      { label: 'C', text: 'reflect the narrator\'s uncertain, fragmented sense of self.' },
      { label: 'D', text: 'provide medical instructions for dementia patients.' },
    ],
    correctAnswer: 2,
    explanation: 'The second-person narration reflects the narrator\'s statement "I\'m not sure there\'s anyone home to narrate"—unable to confidently say "I," the narrator uses "you," embodying the uncertain, fragmented identity the passage explores. This stylistic choice mirrors the thematic content about dissolving selfhood.',
    hint: 'Connect the unusual point of view to what the passage says about the narrator\'s sense of self.',
    difficulty: 5,
    skillIds: ['rhetoric.text_structure', 'passage_type_proficiency.literature_passages'],
  },
  {
    id: Q(105),
    passageId: P(20),
    stem: 'The phrase "ice surrenders to water surrenders to vapor" is used primarily to',
    choices: [
      { label: 'A', text: 'illustrate the physical process of phase changes in matter.' },
      { label: 'B', text: 'represent the natural, gradual transformation of identity.' },
      { label: 'C', text: 'suggest that memory loss follows predictable scientific stages.' },
      { label: 'D', text: 'indicate the narrator is experiencing confusion about basic concepts.' },
    ],
    correctAnswer: 1,
    explanation: 'This metaphor appears when the narrator describes finding "relief in the dissolution of certainty." The progression from solid (ice) to liquid (water) to gas (vapor) represents increasingly fluid, less defined states, mirroring the narrator\'s experience of identity becoming less fixed and certain—a transformation rather than a loss.',
    hint: 'Consider where this phrase appears and what the narrator is expressing about their experience at that moment.',
    difficulty: 4,
    skillIds: ['rhetoric.purpose', 'passage_type_proficiency.literature_passages'],
  },
  {
    id: Q(106),
    passageId: P(20),
    stem: 'The passage\'s conclusion suggests that the narrator has come to view identity as',
    choices: [
      { label: 'A', text: 'something that must be recovered through medical treatment.' },
      { label: 'B', text: 'a collection of disconnected moments rather than a continuous self.' },
      { label: 'C', text: 'an illusion that causes unnecessary suffering.' },
      { label: 'D', text: 'less important than maintaining relationships with loved ones.' },
    ],
    correctAnswer: 1,
    explanation: 'The final paragraph explicitly states: "Maybe identity was never about continuity but about these disconnected moments that briefly flare with recognition. Maybe you\'re not losing yourself but discovering that there was never a self to lose, only this procession of instants pretending to be a life."',
    hint: 'The last paragraph directly states what the narrator has concluded about the nature of identity.',
    difficulty: 4,
    skillIds: ['information_ideas.command_of_evidence', 'passage_type_proficiency.literature_passages'],
  },

  // P21: The Swim Meet (Q107-Q112)
  {
    id: Q(107),
    passageId: P(21),
    stem: 'The central conflict in the passage is best described as',
    choices: [
      { label: 'A', text: 'a swimmer\'s struggle to overcome her physical limitations.' },
      { label: 'B', text: 'the tension between friendship and competition.' },
      { label: 'C', text: 'a coach\'s decision to favor one athlete over another.' },
      { label: 'D', text: 'the pressure to succeed at a championship swim meet.' },
    ],
    correctAnswer: 1,
    explanation: 'The passage centers on how the narrator\'s improvement creates a rift in her friendship with Jenna. Their relationship shifts from collaborative ("her victories felt partly mine") to competitive and distant, culminating in them standing on adjacent blocks "as competitors rather than teammates."',
    hint: 'Focus on the relationship between the two swimmers and how it changes throughout the passage.',
    difficulty: 2,
    skillIds: ['information_ideas.central_ideas', 'passage_type_proficiency.literature_passages'],
  },
  {
    id: Q(108),
    passageId: P(21),
    stem: 'As used in the passage, "unreadable" most nearly means',
    choices: [
      { label: 'A', text: 'illegible.' },
      { label: 'B', text: 'difficult to interpret.' },
      { label: 'C', text: 'uninteresting.' },
      { label: 'D', text: 'invisible.' },
    ],
    correctAnswer: 1,
    explanation: 'Jenna\'s face being "unreadable behind her goggles" means the narrator cannot interpret or understand Jenna\'s emotions. While goggles might obscure facial features (making them literally hard to see), the context emphasizes the narrator\'s inability to understand what Jenna is feeling.',
    hint: 'Consider what the narrator is trying to do when she finds Jenna\'s face "unreadable."',
    difficulty: 2,
    skillIds: ['rhetoric.words_in_context', 'passage_type_proficiency.literature_passages'],
  },
  {
    id: Q(109),
    passageId: P(21),
    stem: 'The passage suggests that the narrator\'s initial attitude toward Jenna\'s victories was one of',
    choices: [
      { label: 'A', text: 'resentment and jealousy.' },
      { label: 'B', text: 'indifference and apathy.' },
      { label: 'C', text: 'genuine happiness and shared pride.' },
      { label: 'D', text: 'competitive determination to surpass her friend.' },
    ],
    correctAnswer: 2,
    explanation: 'The narrator explicitly states, "I didn\'t mind—we were best friends, and her victories felt partly mine." This shows genuine happiness and a sense of shared achievement rather than negative emotions like resentment or indifference.',
    hint: 'Look at what the narrator explicitly says about her feelings when Jenna used to win.',
    difficulty: 1,
    skillIds: ['information_ideas.command_of_evidence', 'passage_type_proficiency.literature_passages'],
  },
  {
    id: Q(110),
    passageId: P(21),
    stem: 'The text message from Jenna can best be characterized as',
    choices: [
      { label: 'A', text: 'enthusiastic and supportive.' },
      { label: 'B', text: 'polite but emotionally distant.' },
      { label: 'C', text: 'passive-aggressive and bitter.' },
      { label: 'D', text: 'confused and uncertain.' },
    ],
    correctAnswer: 1,
    explanation: 'The message says "Good luck today. You\'ll be great," which is polite and positive on the surface. However, the narrator notes there\'s "No mention of her own races, no suggestion we meet early to warm up together like we always did," indicating emotional distance from their usual closeness.',
    hint: 'Consider both what the message says and what the narrator notes is missing from it.',
    difficulty: 3,
    skillIds: ['information_ideas.inferences', 'passage_type_proficiency.literature_passages'],
  },
  {
    id: Q(111),
    passageId: P(21),
    stem: 'The phrase "the water swallowing whatever words I might have found" serves primarily to',
    choices: [
      { label: 'A', text: 'describe the physical difficulty of talking while swimming.' },
      { label: 'B', text: 'symbolize the lost opportunity for communication and reconciliation.' },
      { label: 'C', text: 'illustrate the narrator\'s fear of the deep water.' },
      { label: 'D', text: 'emphasize the intensity of the competitive atmosphere.' },
    ],
    correctAnswer: 1,
    explanation: 'The narrator wanted "to reach over and say something, anything to bridge the sudden gulf between us," but the starting buzzer sounds before she can. The water "swallowing" her words symbolizes how the opportunity for communication is lost, and they must now compete rather than connect.',
    hint: 'Think about what the narrator wanted to do but couldn\'t, and what the water represents in this metaphor.',
    difficulty: 3,
    skillIds: ['rhetoric.purpose', 'passage_type_proficiency.literature_passages'],
  },
  {
    id: Q(112),
    passageId: P(21),
    stem: 'Which choice best describes how the passage\'s structure reinforces its meaning?',
    choices: [
      { label: 'A', text: 'The chronological progression from past to present mirrors the deterioration of the friendship.' },
      { label: 'B', text: 'The alternating perspectives between the two swimmers show both sides of the conflict.' },
      { label: 'C', text: 'The flashback technique emphasizes the narrator\'s regret about her success.' },
      { label: 'D', text: 'The circular structure shows that the friendship will eventually be restored.' },
    ],
    correctAnswer: 0,
    explanation: 'The passage moves chronologically from "since we were eight" through "this year" to "the morning of the championship meet," mirroring how the friendship gradually deteriorates from close collaboration to competitive distance. This linear progression structurally reinforces the theme of growing separation.',
    hint: 'Notice how the passage moves through time and what happens to the friendship at each stage.',
    difficulty: 3,
    skillIds: ['rhetoric.text_structure', 'passage_type_proficiency.literature_passages'],
  },
];
