import { PassageType } from '../entities/passage.entity';

const P = (n: number) => `00000000-0000-0000-0000-${n.toString().padStart(12, '0')}`;
const Q = (n: number) => `10000000-0000-0000-0000-${n.toString().padStart(12, '0')}`;

export const historyPassages = [
  {
    id: P(22),
    title: 'The Printing Press Revolution',
    type: PassageType.HISTORY,
    difficulty: 2,
    source: 'Adapted from historical accounts of printing technology',
    text: `In 1450, Johannes Gutenberg introduced the movable-type printing press to Europe, launching a revolution in communication that would reshape society. Before this innovation, books were painstakingly copied by hand, making them rare and expensive. A single Bible could take months to produce and cost as much as a farm. Gutenberg's press could print hundreds of pages in the time it took a scribe to copy one.

The social consequences were profound. As books became affordable, literacy rates soared. Ideas that had been confined to monasteries and universities spread to merchants, artisans, and farmers. The printing press enabled the Protestant Reformation by allowing Martin Luther's critiques to reach millions. It facilitated the Scientific Revolution by letting researchers share findings quickly. Even governance changed—printed laws and decrees meant citizens could read the rules for themselves rather than relying on officials' interpretations. Within fifty years of Gutenberg's invention, printing presses operated in over 250 European cities, and an estimated 20 million books had been produced. This "information revolution" laid the groundwork for the modern world.`,
    wordCount: 200,
    reviewStatus: 'approved',
  },
  {
    id: P(23),
    title: 'A Voice Against Slavery',
    type: PassageType.HISTORY,
    difficulty: 3,
    source: 'Adapted from an 1850 abolitionist speech',
    text: `My friends, we gather today not as Northerners or Southerners, but as Americans bound by a common creed—that all men are created equal. Yet how hollow those words ring when three million souls toil in bondage! We are told that slavery is a "peculiar institution," a relic that will fade with time. But I say to you: injustice delayed is injustice multiplied. Every day we wait, another generation is born into chains.

Some claim that immediate abolition would bring economic ruin. I remind them that no economy built on human suffering can be called prosperous. What profit is there in cotton and tobacco if we lose our nation's soul? Others argue that enslaved people are unprepared for freedom. This reasoning is as circular as it is cruel—deny education, then cite ignorance as justification for continued oppression.

The path forward is clear, though difficult. We must amend our Constitution to abolish slavery throughout this land. We must compensate those who have suffered, not those who have profited from suffering. And we must extend the full rights of citizenship to all people, regardless of race. Future generations will judge us not by our words, but by our courage to act on our convictions.`,
    wordCount: 210,
    reviewStatus: 'approved',
  },
  {
    id: P(24),
    title: 'Women and the Industrial Revolution',
    type: PassageType.HISTORY,
    difficulty: 4,
    source: 'Adapted from historical labor studies',
    text: `The Industrial Revolution is often narrated as a story of male inventors and industrialists, yet women formed the backbone of the factory system that transformed 19th-century Britain. In textile mills—the era's dominant industry—women comprised up to 60% of the workforce. They operated power looms, managed spinning machines, and performed the intricate tasks that mass production demanded. Their labor was simultaneously essential and exploited: women earned roughly half the wages of men performing comparable work.

This employment pattern reflected economic calculation rather than technological necessity. Factory owners recognized that societal constraints gave them leverage over female workers, who had fewer employment alternatives than men. The resulting wage differential reduced production costs while maximizing profits. Paradoxically, factory work offered women unprecedented economic autonomy. For the first time, significant numbers of working-class women earned independent incomes, enabling some to delay or avoid marriages that might have been economically compulsory in an agrarian society.

The mills also became sites of nascent labor organization. Women workers participated in strikes, though their activism has been systematically underreported by historians who focused on male-dominated trade unions. These early labor actions established precedents that would inform later movements for both workers' rights and women's suffrage, illustrating how economic transformation can catalyze broader social change.`,
    wordCount: 220,
    reviewStatus: 'approved',
  },
  {
    id: P(25),
    title: 'Religious Liberty in the New Republic',
    type: PassageType.HISTORY,
    difficulty: 5,
    source: 'Adapted from Thomas Jefferson\'s 1779 Virginia Statute for Religious Freedom',
    text: `Whereas Almighty God hath created the mind free; that all attempts to influence it by temporal punishments or burthens, or by civil incapacitations, tend only to beget habits of hypocrisy and meanness, and are a departure from the plan of the Holy author of our religion, who being Lord both of body and mind, yet chose not to propagate it by coercions on either, as was in his Almighty power to do.

Be it enacted by the General Assembly that no man shall be compelled to frequent or support any religious worship, place, or ministry whatsoever, nor shall be enforced, restrained, molested, or burthened in his body or goods, nor shall otherwise suffer on account of his religious opinions or belief; but that all men shall be free to profess, and by argument to maintain, their opinion in matters of religion, and that the same shall in no wise diminish, enlarge, or affect their civil capacities.

Though we well know that this Assembly, elected by the people for the ordinary purposes of legislation only, have no power to restrain the acts of succeeding Assemblies, we are free to declare that the rights hereby asserted are of the natural rights of mankind, and that if any act shall be hereafter passed to repeal the present or to narrow its operation, such act will be an infringement of natural right.`,
    wordCount: 230,
    reviewStatus: 'approved',
  },
  {
    id: P(26),
    title: 'The Library of Alexandria',
    type: PassageType.HISTORY,
    difficulty: 1,
    source: 'Adapted from ancient history sources',
    text: `Around 300 BCE, the city of Alexandria in Egypt became home to the ancient world's greatest library. Founded by King Ptolemy I, the Library of Alexandria aimed to collect all the knowledge in the world. Scholars traveled across the Mediterranean to bring back books, scrolls, and manuscripts. Ship captains arriving at Alexandria's harbor were required to surrender any books on board; scribes would copy the texts and return the copies to the owners, keeping the originals for the library.

At its peak, the library held an estimated 500,000 scrolls. It wasn't just a storage space—it was a vibrant research center. Scientists, mathematicians, poets, and philosophers came to study, debate, and share ideas. The mathematician Euclid developed his theories of geometry there. The astronomer Aristarchus proposed that Earth orbits the sun, centuries before Copernicus.

Tragically, the library was destroyed, though historians debate exactly when and how. Some blame Julius Caesar's invasion in 48 BCE, others point to later conflicts. Regardless, the loss was immense. Countless works of literature, science, and philosophy vanished forever, reminding us how fragile human knowledge can be.`,
    wordCount: 190,
    reviewStatus: 'approved',
  },
];

export const historyQuestions = [
  // P22: The Printing Press Revolution (Q113-Q118)
  {
    id: Q(113),
    passageId: P(22),
    stem: 'Which choice best describes the main purpose of the passage?',
    choices: [
      { label: 'A', text: 'To explain the technical process Gutenberg used to create movable type' },
      { label: 'B', text: 'To argue that the printing press was more important than other inventions' },
      { label: 'C', text: 'To describe how the printing press transformed European society' },
      { label: 'D', text: 'To compare manuscript production with modern printing methods' },
    ],
    correctAnswer: 2,
    explanation: 'The passage focuses on the "social consequences" and revolutionary impact of the printing press on literacy, religious reform, science, and governance—all societal transformations. While it mentions technical aspects, the main emphasis is on social change.',
    hint: 'Look at what the passage spends most of its time discussing—technical details or broader societal impacts?',
    difficulty: 2,
    skillIds: ['information_ideas.central_ideas', 'passage_type_proficiency.history_passages'],
  },
  {
    id: Q(114),
    passageId: P(22),
    stem: 'As used in the passage, "confined" most nearly means',
    choices: [
      { label: 'A', text: 'imprisoned' },
      { label: 'B', text: 'restricted' },
      { label: 'C', text: 'compressed' },
      { label: 'D', text: 'defined' },
    ],
    correctAnswer: 1,
    explanation: 'In context, "ideas that had been confined to monasteries and universities" means ideas were restricted or limited to those locations. While "confined" can mean imprisoned, "restricted" better captures the limitation of access described here.',
    hint: 'Consider what happened to ideas after the printing press—they spread beyond their previous limitations.',
    difficulty: 2,
    skillIds: ['rhetoric.words_in_context', 'passage_type_proficiency.history_passages'],
  },
  {
    id: Q(115),
    passageId: P(22),
    stem: 'The passage suggests that before the printing press, most citizens understood laws primarily through',
    choices: [
      { label: 'A', text: 'reading handwritten legal documents' },
      { label: 'B', text: 'attending university courses on law' },
      { label: 'C', text: 'listening to officials explain them' },
      { label: 'D', text: 'studying in monastery libraries' },
    ],
    correctAnswer: 2,
    explanation: 'The passage states that printed laws meant "citizens could read the rules for themselves rather than relying on officials\' interpretations," implying that before printing, citizens depended on officials to explain laws to them.',
    hint: 'What does the passage say changed when laws became printed and accessible?',
    difficulty: 3,
    skillIds: ['information_ideas.inferences', 'passage_type_proficiency.history_passages'],
  },
  {
    id: Q(116),
    passageId: P(22),
    stem: 'Which choice provides the best evidence that the printing press had rapid geographic spread?',
    choices: [
      { label: 'A', text: 'The description of how quickly a printing press could produce pages' },
      { label: 'B', text: 'The reference to Martin Luther\'s critiques reaching millions' },
      { label: 'C', text: 'The statement that presses operated in over 250 cities within fifty years' },
      { label: 'D', text: 'The claim that books became affordable' },
    ],
    correctAnswer: 2,
    explanation: 'The statement about presses operating "in over 250 European cities" within fifty years directly demonstrates rapid geographic expansion. The other choices relate to impact and speed of production, but don\'t specifically address geographic spread.',
    hint: 'Which piece of evidence specifically tells you about the printing press spreading to many different places?',
    difficulty: 2,
    skillIds: ['information_ideas.command_of_evidence', 'passage_type_proficiency.history_passages'],
  },
  {
    id: Q(117),
    passageId: P(22),
    stem: 'The passage indicates that the printing press contributed to the Protestant Reformation by',
    choices: [
      { label: 'A', text: 'allowing churches to print more Bibles' },
      { label: 'B', text: 'enabling Luther\'s ideas to reach a wide audience' },
      { label: 'C', text: 'making monastery libraries obsolete' },
      { label: 'D', text: 'reducing the cost of religious education' },
    ],
    correctAnswer: 1,
    explanation: 'The passage explicitly states that "The printing press enabled the Protestant Reformation by allowing Martin Luther\'s critiques to reach millions." This directly links the press\'s distribution capability to the Reformation\'s success.',
    hint: 'Look for the sentence that directly mentions the Protestant Reformation and explains the connection.',
    difficulty: 2,
    skillIds: ['information_ideas.command_of_evidence', 'passage_type_proficiency.history_passages'],
  },
  {
    id: Q(118),
    passageId: P(22),
    stem: 'The author includes the comparison of a Bible\'s cost to "a farm" primarily to',
    choices: [
      { label: 'A', text: 'illustrate how expensive books were before the printing press' },
      { label: 'B', text: 'explain why farmers could not read' },
      { label: 'C', text: 'show that agriculture was the main economic activity' },
      { label: 'D', text: 'argue that religious texts should be free' },
    ],
    correctAnswer: 0,
    explanation: 'The comparison to "a farm" provides a concrete example of just how expensive hand-copied books were, making them inaccessible to most people. This sets up the contrast with the affordability that the printing press enabled.',
    hint: 'Why would the author use such a dramatic comparison? What point about books before the printing press is being emphasized?',
    difficulty: 2,
    skillIds: ['rhetoric.purpose', 'passage_type_proficiency.history_passages'],
  },

  // P23: A Voice Against Slavery (Q119-Q124)
  {
    id: Q(119),
    passageId: P(23),
    stem: 'The primary purpose of the speech is to',
    choices: [
      { label: 'A', text: 'document the historical origins of slavery in America' },
      { label: 'B', text: 'persuade the audience to support immediate abolition' },
      { label: 'C', text: 'describe the daily experiences of enslaved people' },
      { label: 'D', text: 'propose economic alternatives to slave labor' },
    ],
    correctAnswer: 1,
    explanation: 'The speaker systematically refutes arguments against abolition and calls for constitutional amendment to end slavery immediately. The persuasive purpose is clear from the rhetorical questions, rebuttals, and call to action.',
    hint: 'Consider what the speaker is trying to get the audience to do, not just what information is being provided.',
    difficulty: 3,
    skillIds: ['rhetoric.purpose', 'passage_type_proficiency.history_passages'],
  },
  {
    id: Q(120),
    passageId: P(23),
    stem: 'As used in the passage, "hollow" most nearly means',
    choices: [
      { label: 'A', text: 'empty' },
      { label: 'B', text: 'echoing' },
      { label: 'C', text: 'insincere' },
      { label: 'D', text: 'concave' },
    ],
    correctAnswer: 2,
    explanation: 'When the speaker says the words "all men are created equal" ring "hollow," they mean the words are insincere or hypocritical given the reality of slavery. The words lack genuine meaning when not backed by action.',
    hint: 'What is the speaker suggesting about words that aren\'t matched by actions?',
    difficulty: 3,
    skillIds: ['rhetoric.words_in_context', 'passage_type_proficiency.history_passages'],
  },
  {
    id: Q(121),
    passageId: P(23),
    stem: 'The speaker characterizes the argument that enslaved people are "unprepared for freedom" as',
    choices: [
      { label: 'A', text: 'economically sound but morally questionable' },
      { label: 'B', text: 'historically accurate but no longer relevant' },
      { label: 'C', text: 'self-contradictory and deliberately cruel' },
      { label: 'D', text: 'well-intentioned but impractical' },
    ],
    correctAnswer: 2,
    explanation: 'The speaker calls this reasoning "as circular as it is cruel," pointing out the contradiction: deny people education, then use their lack of education to justify continued enslavement. The speaker sees this as both illogical and deliberately harmful.',
    hint: 'Look at the specific words the speaker uses to describe this argument in the second paragraph.',
    difficulty: 4,
    skillIds: ['rhetoric.arguments', 'passage_type_proficiency.history_passages'],
  },
  {
    id: Q(122),
    passageId: P(23),
    stem: 'Which statement best describes the speaker\'s response to economic arguments for slavery?',
    choices: [
      { label: 'A', text: 'The speaker acknowledges economic concerns but argues moral considerations are more important' },
      { label: 'B', text: 'The speaker dismisses economic arguments as completely fabricated' },
      { label: 'C', text: 'The speaker proposes a gradual economic transition to free labor' },
      { label: 'D', text: 'The speaker suggests that slavery is actually economically inefficient' },
    ],
    correctAnswer: 0,
    explanation: 'The speaker acknowledges that "some claim" abolition would bring economic ruin but then argues that moral considerations trump economic ones: "no economy built on human suffering can be called prosperous." This shows recognition of the argument but prioritization of morality.',
    hint: 'Does the speaker deny that there might be economic impacts, or does the speaker say something else matters more?',
    difficulty: 3,
    skillIds: ['rhetoric.arguments', 'passage_type_proficiency.history_passages'],
  },
  {
    id: Q(123),
    passageId: P(23),
    stem: 'The speaker\'s call to "compensate those who have suffered, not those who have profited from suffering" suggests that',
    choices: [
      { label: 'A', text: 'former slaveholders should receive payment for lost property' },
      { label: 'B', text: 'freed people should receive reparations while slaveholders should not' },
      { label: 'C', text: 'both enslaved people and slaveholders should be compensated equally' },
      { label: 'D', text: 'economic compensation is less important than legal rights' },
    ],
    correctAnswer: 1,
    explanation: 'The speaker draws a clear distinction: "those who have suffered" (enslaved people) should be compensated, while "those who have profited from suffering" (slaveholders) should not. This explicitly rejects compensation for slaveholders while advocating for it for the formerly enslaved.',
    hint: 'Who does the speaker identify as having "suffered" and who as having "profited from suffering"?',
    difficulty: 3,
    skillIds: ['information_ideas.inferences', 'passage_type_proficiency.history_passages'],
  },
  {
    id: Q(124),
    passageId: P(23),
    stem: 'The phrase "injustice delayed is injustice multiplied" primarily functions to',
    choices: [
      { label: 'A', text: 'explain why gradual emancipation is preferable to immediate abolition' },
      { label: 'B', text: 'emphasize the urgency of ending slavery without further delay' },
      { label: 'C', text: 'describe how slavery became more widespread over time' },
      { label: 'D', text: 'argue that slavery has historical roots in multiple injustices' },
    ],
    correctAnswer: 1,
    explanation: 'This phrase counters those who say slavery will "fade with time" by arguing that waiting makes the injustice worse, not better. The speaker uses this to support immediate rather than gradual action.',
    hint: 'This phrase comes right after someone says slavery will fade on its own. What is the speaker\'s response to that idea?',
    difficulty: 3,
    skillIds: ['rhetoric.purpose', 'passage_type_proficiency.history_passages'],
  },

  // P24: Women and the Industrial Revolution (Q125-Q130)
  {
    id: Q(125),
    passageId: P(24),
    stem: 'The main idea of the passage is that women workers during the Industrial Revolution',
    choices: [
      { label: 'A', text: 'were essential to industrial production despite being exploited and overlooked' },
      { label: 'B', text: 'invented many of the technologies that powered textile mills' },
      { label: 'C', text: 'earned wages comparable to men in similar factory positions' },
      { label: 'D', text: 'preferred factory work to agricultural labor' },
    ],
    correctAnswer: 0,
    explanation: 'The passage emphasizes that women were crucial to factories (forming 60% of textile workers) yet were exploited through lower wages and have been underreported by historians. This combination of essential contribution and exploitation/erasure is the central theme.',
    hint: 'Notice how the passage begins by saying women are left out of the typical narrative, then describes their importance and the challenges they faced.',
    difficulty: 4,
    skillIds: ['information_ideas.central_ideas', 'passage_type_proficiency.history_passages'],
  },
  {
    id: Q(126),
    passageId: P(24),
    stem: 'As used in the passage, "leverage" most nearly means',
    choices: [
      { label: 'A', text: 'mechanical advantage' },
      { label: 'B', text: 'negotiating power' },
      { label: 'C', text: 'financial investment' },
      { label: 'D', text: 'physical strength' },
    ],
    correctAnswer: 1,
    explanation: 'In this context, "societal constraints gave them leverage over female workers" means factory owners had negotiating power or advantage. The constraints on women\'s options allowed owners to pay lower wages.',
    hint: 'Think about what allowed factory owners to pay women less—what kind of advantage did they have?',
    difficulty: 4,
    skillIds: ['rhetoric.words_in_context', 'passage_type_proficiency.history_passages'],
  },
  {
    id: Q(127),
    passageId: P(24),
    stem: 'According to the passage, factory owners paid women less than men primarily because',
    choices: [
      { label: 'A', text: 'women performed less complex tasks than male workers' },
      { label: 'B', text: 'technological limitations prevented women from working full-time' },
      { label: 'C', text: 'social constraints limited women\'s employment alternatives' },
      { label: 'D', text: 'women requested lower wages in exchange for better working conditions' },
    ],
    correctAnswer: 2,
    explanation: 'The passage explicitly states that wage differences "reflected economic calculation rather than technological necessity" and that "societal constraints gave them leverage over female workers, who had fewer employment alternatives than men."',
    hint: 'The passage directly addresses why women were paid less—look for the explanation in the second paragraph.',
    difficulty: 3,
    skillIds: ['information_ideas.command_of_evidence', 'passage_type_proficiency.history_passages'],
  },
  {
    id: Q(128),
    passageId: P(24),
    stem: 'The passage suggests that factory work was "paradoxical" for women because it',
    choices: [
      { label: 'A', text: 'required both physical strength and technical skill' },
      { label: 'B', text: 'was simultaneously exploitative and economically liberating' },
      { label: 'C', text: 'paid poorly but offered high social status' },
      { label: 'D', text: 'was both dangerous and carefully regulated' },
    ],
    correctAnswer: 1,
    explanation: 'The passage describes a paradox: women\'s labor was "essential and exploited" with low wages, yet factory work also gave women "unprecedented economic autonomy" and independent incomes. These seemingly contradictory effects make the situation paradoxical.',
    hint: 'What two contrasting aspects of factory work does the passage discuss—what was negative and what was positive?',
    difficulty: 4,
    skillIds: ['information_ideas.inferences', 'passage_type_proficiency.history_passages'],
  },
  {
    id: Q(129),
    passageId: P(24),
    stem: 'Which choice best describes the structure of the passage?',
    choices: [
      { label: 'A', text: 'A chronological narrative of technological developments' },
      { label: 'B', text: 'An analysis that examines exploitation, economic impact, and political legacy' },
      { label: 'C', text: 'A comparison between male and female factory experiences' },
      { label: 'D', text: 'A debate presenting multiple historians\' interpretations' },
    ],
    correctAnswer: 1,
    explanation: 'The passage moves through three distinct analytical points: exploitation through wage discrimination (paragraph 1-2), economic autonomy paradox (paragraph 2), and connection to labor/suffrage movements (paragraph 3). It\'s analytical rather than chronological or comparative.',
    hint: 'Look at how each paragraph develops a different aspect of women\'s factory work—what are the three main topics?',
    difficulty: 4,
    skillIds: ['rhetoric.text_structure', 'passage_type_proficiency.history_passages'],
  },
  {
    id: Q(130),
    passageId: P(24),
    stem: 'The author suggests that women\'s labor activism has been "systematically underreported" in order to',
    choices: [
      { label: 'A', text: 'criticize historians for focusing on male-dominated unions' },
      { label: 'B', text: 'argue that women workers were more militant than men' },
      { label: 'C', text: 'explain why textile strikes were unsuccessful' },
      { label: 'D', text: 'prove that women did not participate in labor movements' },
    ],
    correctAnswer: 0,
    explanation: 'The passage states activism "has been systematically underreported by historians who focused on male-dominated trade unions," which is a direct critique of historical scholarship for overlooking women\'s contributions. The phrase "systematically underreported" implies deliberate or biased exclusion.',
    hint: 'Why does the author mention that historians focused on male-dominated unions? What point is being made about historical scholarship?',
    difficulty: 4,
    skillIds: ['rhetoric.purpose', 'passage_type_proficiency.history_passages'],
  },

  // P25: Religious Liberty in the New Republic (Q131-Q136)
  {
    id: Q(131),
    passageId: P(25),
    stem: 'The primary purpose of this statute is to',
    choices: [
      { label: 'A', text: 'establish an official state religion for Virginia' },
      { label: 'B', text: 'protect religious freedom and separate church from state power' },
      { label: 'C', text: 'require all citizens to attend religious services' },
      { label: 'D', text: 'outline proper procedures for religious worship' },
    ],
    correctAnswer: 1,
    explanation: 'The statute explicitly states that "no man shall be compelled to frequent or support any religious worship" and that religious opinions shall not "affect their civil capacities." This establishes religious freedom and prevents government enforcement of religious practices.',
    hint: 'Look at what the statute says people shall NOT be forced to do regarding religion.',
    difficulty: 4,
    skillIds: ['information_ideas.central_ideas', 'passage_type_proficiency.history_passages'],
  },
  {
    id: Q(132),
    passageId: P(25),
    stem: 'As used in the passage, "temporal" most nearly means',
    choices: [
      { label: 'A', text: 'temporary' },
      { label: 'B', text: 'worldly' },
      { label: 'C', text: 'timely' },
      { label: 'D', text: 'chronological' },
    ],
    correctAnswer: 1,
    explanation: '"Temporal punishments" refers to earthly, worldly, or civil penalties imposed by government (as opposed to spiritual consequences). The statute argues that government should not use worldly punishments to influence religious belief.',
    hint: 'The passage contrasts what governments do with what God chose to do. What kind of punishments can governments impose?',
    difficulty: 5,
    skillIds: ['rhetoric.words_in_context', 'passage_type_proficiency.history_passages'],
  },
  {
    id: Q(133),
    passageId: P(25),
    stem: 'The statute\'s argument that God "chose not to propagate [religion] by coercions" primarily functions to',
    choices: [
      { label: 'A', text: 'prove that religious freedom is divinely mandated' },
      { label: 'B', text: 'suggest that religious beliefs cannot be changed' },
      { label: 'C', text: 'argue that if God respects free will, governments should too' },
      { label: 'D', text: 'explain why some religions use force to gain converts' },
    ],
    correctAnswer: 2,
    explanation: 'The rhetorical strategy here is: if God, who has the power to force belief, chose not to do so, then human governments certainly shouldn\'t either. It\'s an argument from divine example that supports religious freedom.',
    hint: 'The passage notes God had the "Almighty power" to force belief but didn\'t. What does this suggest about government power?',
    difficulty: 5,
    skillIds: ['rhetoric.arguments', 'passage_type_proficiency.history_passages'],
  },
  {
    id: Q(134),
    passageId: P(25),
    stem: 'According to the statute, religious opinions should have what effect on a person\'s civil rights?',
    choices: [
      { label: 'A', text: 'They should determine which rights a person receives' },
      { label: 'B', text: 'They should enhance the rights of religious citizens' },
      { label: 'C', text: 'They should have no effect whatsoever' },
      { label: 'D', text: 'They should be considered when granting certain privileges' },
    ],
    correctAnswer: 2,
    explanation: 'The statute explicitly states that religious opinions "shall in no wise diminish, enlarge, or affect their civil capacities"—meaning religious views should have zero impact on civil rights.',
    hint: 'Look for the specific phrase about whether religious opinions "diminish, enlarge, or affect" something.',
    difficulty: 4,
    skillIds: ['information_ideas.command_of_evidence', 'passage_type_proficiency.history_passages'],
  },
  {
    id: Q(135),
    passageId: P(25),
    stem: 'The final paragraph suggests that the Assembly includes it because',
    choices: [
      { label: 'A', text: 'they expect future assemblies to support religious freedom' },
      { label: 'B', text: 'they want to make the statute difficult to repeal' },
      { label: 'C', text: 'they acknowledge they cannot legally bind future legislators but want to assert the moral principle' },
      { label: 'D', text: 'they believe natural rights can be revoked by legislation' },
    ],
    correctAnswer: 2,
    explanation: 'The passage acknowledges the Assembly "have no power to restrain the acts of succeeding Assemblies" but nevertheless declares these rights are "natural rights" and that any future repeal "will be an infringement of natural right." They\'re making a moral statement despite lacking legal power to bind future lawmakers.',
    hint: 'Notice the contrast between what the Assembly admits it cannot do legally and what it declares anyway.',
    difficulty: 5,
    skillIds: ['information_ideas.inferences', 'passage_type_proficiency.history_passages'],
  },
  {
    id: Q(136),
    passageId: P(25),
    stem: 'The statute categorizes religious freedom as a "natural right" in order to',
    choices: [
      { label: 'A', text: 'distinguish it from rights granted by government' },
      { label: 'B', text: 'suggest it applies only to certain religious groups' },
      { label: 'C', text: 'indicate it can be modified by future legislation' },
      { label: 'D', text: 'show it is based on scientific principles' },
    ],
    correctAnswer: 0,
    explanation: 'By calling it a "natural right," the statute places religious freedom in a category of fundamental rights that exist independently of government—governments can only recognize or violate them, not create or legitimately revoke them. This is distinct from rights created by legislation.',
    hint: 'What is the significance of calling something a "natural" right rather than just a legal right?',
    difficulty: 5,
    skillIds: ['rhetoric.purpose', 'passage_type_proficiency.history_passages'],
  },

  // P26: The Library of Alexandria (Q137-Q142)
  {
    id: Q(137),
    passageId: P(26),
    stem: 'The passage primarily focuses on',
    choices: [
      { label: 'A', text: 'the architectural design of the Library of Alexandria' },
      { label: 'B', text: 'the significance and tragic loss of the Library of Alexandria' },
      { label: 'C', text: 'the debate among historians about when the library was destroyed' },
      { label: 'D', text: 'comparing the Library of Alexandria to modern libraries' },
    ],
    correctAnswer: 1,
    explanation: 'The passage describes the library\'s founding, its impressive collection and role as a research center, and its eventual destruction—emphasizing both its importance and the tragedy of its loss. The historical debate is mentioned but is not the main focus.',
    hint: 'Consider what the passage emphasizes most: how the library was destroyed, or what made it important and why its loss mattered?',
    difficulty: 1,
    skillIds: ['information_ideas.central_ideas', 'passage_type_proficiency.history_passages'],
  },
  {
    id: Q(138),
    passageId: P(26),
    stem: 'As used in the passage, "vibrant" most nearly means',
    choices: [
      { label: 'A', text: 'colorful' },
      { label: 'B', text: 'loud' },
      { label: 'C', text: 'active' },
      { label: 'D', text: 'shaking' },
    ],
    correctAnswer: 2,
    explanation: 'The passage describes the library as a "vibrant research center" where scholars came to "study, debate, and share ideas." In this context, "vibrant" means active, lively, or full of intellectual activity.',
    hint: 'What kind of research center is being described—one with a lot of activity or one with bright colors?',
    difficulty: 1,
    skillIds: ['rhetoric.words_in_context', 'passage_type_proficiency.history_passages'],
  },
  {
    id: Q(139),
    passageId: P(26),
    stem: 'According to the passage, what happened to books that ship captains brought to Alexandria?',
    choices: [
      { label: 'A', text: 'They were purchased by the library at fair prices' },
      { label: 'B', text: 'They were copied, with originals kept and copies returned to owners' },
      { label: 'C', text: 'They were returned immediately after being catalogued' },
      { label: 'D', text: 'They were destroyed if they contained controversial ideas' },
    ],
    correctAnswer: 1,
    explanation: 'The passage states that "scribes would copy the texts and return the copies to the owners, keeping the originals for the library." This was the library\'s method for acquiring books from ships.',
    hint: 'Read carefully—did the owners get their original books back, or did they get something else?',
    difficulty: 1,
    skillIds: ['information_ideas.command_of_evidence', 'passage_type_proficiency.history_passages'],
  },
  {
    id: Q(140),
    passageId: P(26),
    stem: 'The passage mentions Euclid and Aristarchus primarily to',
    choices: [
      { label: 'A', text: 'prove that the library contained scientific texts' },
      { label: 'B', text: 'illustrate the important research conducted at the library' },
      { label: 'C', text: 'show that ancient scientists were more advanced than previously thought' },
      { label: 'D', text: 'explain why the library was eventually destroyed' },
    ],
    correctAnswer: 1,
    explanation: 'These examples of groundbreaking work (Euclid\'s geometry, Aristarchus\'s heliocentric theory) serve to demonstrate the significance of the research happening at the library, supporting the point that it was a vital intellectual center.',
    hint: 'Why would the author mention specific scholars and their achievements? What point is being made about the library itself?',
    difficulty: 2,
    skillIds: ['rhetoric.purpose', 'passage_type_proficiency.history_passages'],
  },
  {
    id: Q(141),
    passageId: P(26),
    stem: 'The passage suggests that historians disagree about',
    choices: [
      { label: 'A', text: 'whether the library actually existed' },
      { label: 'B', text: 'how many scrolls the library contained' },
      { label: 'C', text: 'the specific circumstances of the library\'s destruction' },
      { label: 'D', text: 'which scholars worked at the library' },
    ],
    correctAnswer: 2,
    explanation: 'The passage states "historians debate exactly when and how" the library was destroyed, mentioning different possible causes. This indicates disagreement about the specific circumstances, not about the library\'s existence or contents.',
    hint: 'What does the passage say historians "debate" about?',
    difficulty: 1,
    skillIds: ['information_ideas.command_of_evidence', 'passage_type_proficiency.history_passages'],
  },
  {
    id: Q(142),
    passageId: P(26),
    stem: 'The final sentence ("Regardless, the loss...can be") primarily serves to',
    choices: [
      { label: 'A', text: 'introduce a new topic about preserving knowledge' },
      { label: 'B', text: 'emphasize the enduring significance of the library\'s destruction' },
      { label: 'C', text: 'argue that the library should be rebuilt' },
      { label: 'D', text: 'criticize historians for their disagreements' },
    ],
    correctAnswer: 1,
    explanation: 'Despite uncertainty about exactly how the library was destroyed, the passage concludes by stressing that "the loss was immense" and reminds us about the fragility of knowledge. This emphasizes the lasting importance and tragedy of the destruction, regardless of its specific cause.',
    hint: 'The word "Regardless" suggests the author is saying something that\'s true no matter what. What point remains important despite the historical uncertainty?',
    difficulty: 2,
    skillIds: ['rhetoric.text_structure', 'passage_type_proficiency.history_passages'],
  },
];
